kubic-project/salt

packaging/suse/make_spec.sh
the actual date is the commit date
=> packaging: fix date

packaging/suse/make_spec.sh
we are fetching now the master tarball from concourse
also the url was wrong
=> packaging: adapt source and url

packaging/suse/make_spec.sh
cd: kubernetes-salt-1.5.3+20170309.41f16e7: No such file or directory
=> packaging: fix name of tarball directory

pillar/kube-master.sls, pillar/params.sls, pillar/top.sls, pillar/vars.sls, salt/kubernetes-master/apiserver.jinja, salt/kubernetes-master/init.sls, salt/kubernetes-minion/kubeconfig.jinja, salt/kubernetes-minion/kubelet.jinja
Some cleanups in the Salt's pillar variables
@ereslibre @jimmykarily Maybe you have to change some things on the velum side...
=> Vars cleanups

pillar/kube-minion.sls, salt/kubernetes-minion/kubelet.jinja
not sure if this is the place where it should go .... but let's start the discussion
=> [WIP] add sles12 pause image

pillar/params.sls, salt/docker/init.sls, salt/kubernetes-master/apiserver.jinja, salt/kubernetes-master/controller-manager.jinja, salt/kubernetes-master/scheduler.jinja, salt/kubernetes-minion/kubelet.jinja, salt/kubernetes-minion/proxy.jinja
=> Configure some components arguments from the pillar

pillar/kube-minion.sls, salt/kubernetes-minion/kubelet.jinja
=> Fixed the infra container path for CaaSP

salt/kubernetes-minion/kubelet.jinja
=> Use FQDN as kubelet hostname

salt/kubernetes-minion/kubeconfig.jinja
Fix a recently merged Jinja2 syntax error.
=> Fix Jinja2 syntax error in kubeconfig.jinja

pillar/params.sls, salt/docker/init.sls
Depends on kubic-project/terraform#56
=> Minor cleanups about the docker registry

config/master.d/master.conf
see https://docs.saltstack.com/en/latest/ref/configuration/master.html#worker-threads
* to avoid minion calls to master timing out
* fixes https://github.com/kubic-project/salt/issues/62
=> bump number of worker threads

pillar/kubelet.sls, pillar/params.sls, salt/haproxy/init.sls, salt/kubelet/init.sls, salt/kubelet/kubelet-initial.jinja, salt/kubelet/kubelet.jinja, salt/kubernetes-master/init.sls
Adding two parameters - region and zone, to use the Kubernetes
scheduler's awareness of zones / regions during scheduling (for affinity
and anti-affinity rules) for HA
=> Adding AZs to bare metal machines

pillar/kube-master.sls, salt/kubernetes-master/init.sls
=> Add apiserver main hostname

salt/repositories/containers.repo, salt/repositories/init.sls
=> Do not create the file if it doesn't exist in other OS than openSUSE Leap

pillar/args.sls, pillar/params.sls, pillar/top.sls, salt/kubernetes-master/apiserver.jinja, salt/kubernetes-master/controller-manager.jinja, salt/kubernetes-master/init.sls, salt/kubernetes-master/scheduler.jinja
Fix: some Jinja templates
Do not really require any extra options for the service/daemons
Reorganize the pillar
=> Fix Jinja templates and minor Pillar reorganization

salt/etcd-proxy/etcd.conf
let me know if you guys find anything out that we can use to avoid doing hacks like this in etcd.
otherwise, PTAL and merge if it's ok.
=> revert changes to etcd systemd drop-in unit

salt/container-feeder/init.sls, salt/top.sls
=> docker: reload container-feeder after starting docker

salt/kubernetes-minion/init.sls
This reverts commit 20cb77866bc1e14c6ef1d59ac5b416126addde4b, reversing
changes made to b76ab05085c4e55224158a6fe75b47d5c851bc0d.
=> Revert TLS everywhere

salt/orch/kubernetes.sls
Currently, we never ask for more than 3 members. Setting this to 3 ensures
we don't let more than 3 members attempt etcd discovery before a cluster
has been fully formed. If we have less this 3, this will still succeed, as
the exact number of members we expect will also end up attempting discovery
at the same time.
=> Set etcd batch size to 3 nodes

salt/kubernetes-master/controller-manager.jinja, salt/kubernetes-master/scheduler.jinja
Don't duplicate log level argument for k8s scheduler and controller
=> Don't duplicate log level argument for k8s scheduler and controller

salt/cert/init.sls
Added:
* kubernetes
* kubernetes.default
* kubernetes.default.svc
=> Add some extra names to the API server certificate (bsc#1033671)

salt/orch/update.sls
These additional requisites enforce a stricter ordering of tasks
during the upgrade. In some case, "-set-update-grain" would not
execute in the right place, potentially leading to a failed
upgrade.
bsc#1045381
Backport of https://github.com/kubic-project/salt/pull/174
=> Add extra requisites to the update orchestration

salt/addons/init.sls, salt/kube-apiserver/init.sls
Refactor the wait-for-apiserver we currently have in `addons/init.sls` and move it to the `kube-apiserver/init.sls` so it can be used in some other parts of the code.
=> Refactor the wait-for-apiserver

salt/addons/init.sls
...kube-dns creation in multi master set up
=> [bsc# 1057552] Fix the race condition that occurs with Kube-DNS creation in multi master environment

salt/addons/addons/kubedns-sa.yaml, salt/addons/addons/kubedns.yaml.jinja, salt/addons/addons/tiller.yaml.jinja, salt/dex/dex.yaml
See commit messages for details
=> Addons - Labels, Annotations, Tolerations cleanup

salt/docker/init.sls, salt/proxy/init.sls
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1053739
=> Do not access infra machines through the proxy (bsc#1053739)

salt/dex/dex.yaml
Rebased on top of https://github.com/kubic-project/salt/pull/235
Depends on: https://github.com/kubic-project/velum/pull/314
Depends on: https://build.opensuse.org/request/show/531671
=>  Set frontend settings: `dir` and `theme`

salt/kubelet/stop.sls
=> Fix missing requirement during the upgrade process

salt/kubelet/stop.sls
Fixes: bsc#1062824
Backport of https://github.com/kubic-project/salt/pull/257
=> [2.0] Fix missing requirement during the upgrade process

salt/etc-hosts/init.sls
See https://github.com/kubic-project/salt/pull/265#issuecomment-337256898
=> Add comment message about keeping update /etc/hosts in velum container

salt/_macros/certs.jinja, salt/cert/init.sls, salt/kube-apiserver/init.sls, salt/kube-controller-manager/init.sls, salt/kube-scheduler/init.sls, salt/velum/init.sls
Try to unify and simplify the certificates generation with the help of some Jinja macros
=> Use some Jinja macros for generating certificates

config/master.d/50-master.conf
See [this issue](https://bugzilla.suse.com/show_bug.cgi?id=1065018).
=> Increase worker threads and backlog length (bsc#1065018)

salt/_states/caasp_retriable.py, salt/etcd/init.sls, salt/flannel/init.sls, salt/haproxy/init.sls, salt/kube-apiserver/init.sls, salt/kubelet/init.sls
Backport of PR #291 
Orchestration is working locally
=> Release 2.0 backport fix random iptables crashes bsc 1064186

config/master.d/50-master.conf
=> [2.0] Increase worker threads and backlog length (bsc#1065018)

pillar/certificates.sls, pillar/params.sls, salt/dex/init.sls, salt/kube-proxy/init.sls, salt/kubectl-config/init.sls, salt/kubelet/init.sls
... like the `kubelet`, `dex` and `kube-proxy` ones (continues the work started in #280)
=> Replace some other certificates by Jinja templates

pillar/params.sls
=> Removed unused flannel iface grain

salt/orch/update.sls
Reverts kubic-project/salt#306. Let's merge it after 2.0 is out.
=> Revert "Generate sa key in the update orchestration"

salt/etc-hosts/hosts.jinja
=> only set service entries for localhost on kube-master

salt/orch/kubernetes.sls, salt/orch/update.sls
We want to sync the pillars on the master first.
=> Sync _pillar modules only

pillar/ip_addrs.sls, pillar/mine.sls, pillar/top.sls, salt/_macros/network.jinja, salt/etc-hosts/hosts.jinja, salt/flannel/flanneld.sysconfig.jinja, salt/haproxy/haproxy.cfg.jinja, salt/kube-apiserver/apiserver.jinja, salt/kube-apiserver/init.sls, salt/kubelet/kubelet.jinja, salt/orch/update.sls
=> [2.0] Remove all the remaining references of eth0 (bsc#1058079)

salt/_macros/certs.jinja
Minor: check if the extra name is != None before trying to check the length
=> Check if the extra name is != None before trying to check the length

salt/addons/init.sls
Fix for [bsc#1072005](https://bugzilla.suse.com/show_bug.cgi?id=1072005)
=> Do not try to create clusterrolebindings when they are already there

salt/dex/dex.yaml
This will fix CI.
Depends on: https://build.opensuse.org/request/show/557306 and its request for IBS.
=> Bump dex version

config/master.d/50-reactor.conf, pillar/beacons.sls, salt/_beacons/default_network_interface_settings.py
=> Add beacon to notify network changes only on the default network interface

config/master.d/50-master.conf, salt/_modules/caasp_etcd.py, salt/_modules/caasp_filters.py, salt/etcd-discovery/init.sls, salt/orch/kubernetes.sls
=> [2.0] Use a batch size for etcd setup equal to the number of etcd masters (bsc#1066695)

pillar/docker.sls, salt/etc-hosts/init.sls
* Docker will no longer accept a `docker cp` over /etc/hosts
* Fix docker package name
=> Fix breakage introduced by docker update

salt/dex/dex.yaml
(cherry picked from commit 1863c0678ef4d554296a361a70aa18c202fc7ca4)
=> [2.0] Bump dex version

pillar/cni.sls
Must be accepted at the same time as https://build.suse.de/request/show/153722
=> Update flannel image tag to match flannel version

salt/_modules/caasp_docker.py
=> [2.0] Make sure we do not crash on pillars that are not properly formatted.

salt/README.md
Feel free to suggest any change or addition...
=> A very basic README on the file naming conventions

salt/etc-hosts/hosts.jinja, salt/ldap/init.sls
feature#net-ldap-cert
https://github.com/kubic-project/caasp-container-manifests/pull/153
=> add ldap.infra.caasp.local to the certificate

salt/haproxy/haproxy.cfg.jinja
See also: https://github.com/kubic-project/caasp-container-manifests/pull/159
=> Haproxy: Remove daemon config flag

salt/_macros/kubectl.jinja, salt/addons/dns/kubedns.yaml.jinja, salt/addons/tiller/tiller.yaml.jinja, salt/cni/kube-flannel.yaml.jinja, salt/dex/dex.yaml, salt/haproxy/init.sls, salt/kube-apiserver/init.sls, salt/kubelet/configure-labels.sls, salt/kubelet/configure-taints.sls, salt/kubelet/init.sls, salt/kubelet/kubelet-initial.jinja, salt/orch/kubernetes.sls, salt/orch/update.sls, salt/top.sls
Masters should be tainted and labelled as masters, rather than setting
these nodes as unschedulable.
=> Taint and Label Masters

salt/orch/update.sls
Make sure the require has at least the latest element that is always present.
=> Do not produce empty `require` list.

salt/kubelet/update-pre-orchestration.sh
Ensure we always exit this script with a salt cmd.run stateful compatible final line.
An alternative to https://github.com/kubic-project/salt/pull/411
=> Add exit handler to kubelet/update-pre-orchestration.sh

salt/orch/update.sls
We need to include the new SAN on all the certificates before restarting
the first machine. Otherwise, this machine (a master) can find itself
isolated without being able to contact any etcd member with the name it
has (as the rest of the nodes haven't updated their certificates yet to
also include the new name on the SAN).
=> Update `etcd` certificates before updating any machine

salt/_modules/caasp_nodes.py, salt/_modules/tests/test_caasp_nodes.py, salt/orch/update-etc-hosts.sls
=> Fix race condition on update-etc-hosts

salt/orch/removal.sls
Configure taints/labels on the replacement node
Fix typo
=> Configure taints/labels on the replacement node

salt/_grains/caasp_nodename.py
Related to https://bugzilla.suse.com/show_bug.cgi?id=1087115
=> Lowercase hostnames

salt/_modules/caasp_etcd.py, salt/_states/caasp_etcd.py, salt/etcd/remove-pre-stop-services.sls, salt/orch/force-removal.sls, salt/orch/update-etc-hosts.sls
This orchestration will try to unregister a node on a best-effort
basis, and is considered to always succeed.
feature#force-node-removal
=> Add force removal orchestration

salt/_modules/caasp_etcd.py
=> Remove unneeded variables

salt/orch/removal.sls
* Always remove the "we-are-removing-a-node" cluster-wide grain.
* Make sure we remove the mine for the target aftrer removing the key (see https://github.com/saltstack/salt/issues/11389 )
=> Node removal: some fixes

salt/_grains/caasp_nodename.py
=> Stop using __opts__ and os_data() 

salt/orch/removal.sls
=> Fix: remove leftover file

pillar/certificates.sls, salt/cni/cilium-config.yaml.jinja, salt/cni/cilium-ds.yaml.jinja, salt/cni/cilium-rbac.yaml.jinja, salt/cni/cilium/init.sls, salt/cni/init.sls, salt/top.sls
*This still depends on cilium container images to be created in OBS
=> cni: add cilium as alternate to flannel plugin

salt/addons/dns/init.sls, salt/addons/psp/init.sls, salt/addons/tiller/deployment-wait.sls, salt/addons/tiller/init.sls, salt/cleanup/remove-post-orchestration.sls, salt/cni/cilium/init.sls, salt/etc-hosts/init.sls, salt/etcd/update-pre-orchestration.sls, salt/etcd/update-pre-reboot.sls, salt/kube-apiserver/apiserver.jinja, salt/transactional-update/init.sls
they need to be globally unique
orch error happened when setting psp to false in params.sls
fix#conflicting-sls-ids
=> [bsc#1092140] enable psp opt-out

salt/addons/dns/init.sls, salt/addons/psp/init.sls, salt/addons/tiller/deployment-wait.sls, salt/addons/tiller/init.sls, salt/cleanup/remove-post-orchestration.sls, salt/cni/cilium/init.sls, salt/etc-hosts/init.sls, salt/etcd/update-pre-orchestration.sls, salt/etcd/update-pre-reboot.sls, salt/kube-apiserver/apiserver.jinja, salt/transactional-update/init.sls
https://github.com/kubic-project/salt/pull/516
=> [3.0] [bsc#1092140] enable psp opt-out

salt/_modules/caasp_cri.py, salt/_modules/caasp_nodes.py, salt/container-feeder/init.sls, salt/haproxy/init.sls, salt/top.sls
Backport of https://github.com/kubic-project/salt/pull/514
=> Make crictl handling more robust

pillar/params.sls, salt/_modules/caasp_pillar.py, salt/kubelet/kubelet.jinja
Backport of https://github.com/kubic-project/salt/pull/518
=> kubelet: allow resource reservation

salt/crio/remove-pre-reboot.sls, salt/crio/stop.sls
Backport of https://github.com/kubic-project/salt/pull/526
=> Add missing cri-o removal states

.gitignore, Jenkinsfile.flake8, README.md, salt/_beacons/default_network_interface_settings.py, salt/_grains/caasp_nodename.py, salt/_modules/caasp_cri.py, salt/_modules/caasp_docker.py, salt/_modules/caasp_etcd.py, salt/_modules/caasp_net.py, salt/_modules/caasp_nodes.py, salt/_modules/caasp_pillar.py, salt/_modules/tests/test_caasp_etcd.py, salt/_modules/tests/test_caasp_pillar.py, salt/_pillar/velum.py, salt/_states/caasp_cmd.py, salt/_states/caasp_cri.py, salt/_states/caasp_etcd.py, salt/_states/caasp_retriable.py, salt/_states/caasp_service.py, tox.ini
Flake8 is a pluggable wrapper around the "standard" python pep8 too for code style enforcement.
=> Add flake8/codestyle job

.gitignore, Jenkinsfile.flake8, README.md, salt/_beacons/default_network_interface_settings.py, salt/_grains/caasp_nodename.py, salt/_modules/caasp_cri.py, salt/_modules/caasp_docker.py, salt/_modules/caasp_etcd.py, salt/_modules/caasp_net.py, salt/_modules/caasp_nodes.py, salt/_modules/caasp_pillar.py, salt/_modules/tests/test_caasp_etcd.py, salt/_modules/tests/test_caasp_pillar.py, salt/_pillar/velum.py, salt/_states/caasp_cmd.py, salt/_states/caasp_cri.py, salt/_states/caasp_etcd.py, salt/_states/caasp_retriable.py, salt/_states/caasp_service.py, tox.ini
Flake8 is a pluggable wrapper around the "standard" python pep8 too for code style enforcement.
=> [3.0] Add flake8/codestyle job

pillar/params.sls, salt/kubelet/kubelet.jinja
feature#compute-resources
https://github.com/kubic-project/velum/pull/514
=> fix eviction-hard path

salt/orch/update.sls
The `salt.function` call will be marked as failed if there were no minions
to target. Make sure that we only run this step if we know that we'll have
some targets available.
Fixes: bsc#1093491
=> Only remove the master grains if there are any masters to be updated.

salt/orch/update.sls
The `salt.function` call will be marked as failed if there were no minions
to target. Make sure that we only run this step if we know that we'll have
some targets available.
Fixes: bsc#1093491
(cherry picked from commit 28fccad520948a149ff0c0fb409b0981c6e1bcd5)
=> [3.0] Only remove the master grains if there are any masters to be updated.

salt/kube-apiserver/apiserver.jinja
=> skip removed etcd servers (bsc#1093305)

salt/cert/init.sls
`cert`-state will install the certificates as trust anchors.
=> Install system wide certificates from pillars.

salt/transactional-update/init.sls, salt/transactional-update/transactional-update.conf
Fixes bsc#1088675
Signed-off-by: Flavio Castelli <fcastelli@suse.com>
(cherry picked from commit b501d9fe5600ab711139dab215bb3e55c5de6fd7)
Backport of https://github.com/kubic-project/salt/pull/549
=> Provide configuration to transactional-update

pillar/kube-master.sls, salt/kube-apiserver/apiserver.jinja, salt/kube-apiserver/init.sls
Backport of https://github.com/kubic-project/salt/pull/541/commits
=> Add support for kube API auditing

salt/addons/dex/init.sls, salt/docker/init.sls, salt/etcd/init.sls, salt/kube-apiserver/init.sls, salt/kube-controller-manager/init.sls, salt/kube-proxy/init.sls, salt/kube-scheduler/init.sls, salt/kubelet/init.sls, salt/kubernetes-common/init.sls, salt/repositories/containers.repo, salt/repositories/init.sls, salt/top.sls
Backport of https://github.com/kubic-project/salt/pull/548
=> Remove unneeded state

pillar/params.sls, salt/kubernetes-common/openstack-config.jinja
=> updated pillar and openstack config to use project and domain ids

salt/docker/init.sls
=> also reload docker when certificates change

salt/_modules/caasp_cri.py
=> Log all CRI issues as we go, and show them if we really timeout

Jenkinsfile.flake8, Jenkinsfile.tests
Run tox based tests using a pre-baked tox container rather than installing things on demand.
=> Run tox based tests using a pre-baked tox container

salt/crio/init.sls, salt/docker/init.sls
=> [3.0] fix docker reload again

packaging/suse/make_spec.sh
* make use of %license macro
* update image prefix for sle15
=> Spec update

salt/_pillar/velum.py
When working on bsc#1093123 I've seen that the orchestration fails becasue 1) haproxy was temporarily down 2) the pillar cannot be accessed 3) `velum.py` crashes with an exception. We can avoid this failure for this kind of transient errors by using the Pillar cache (when present).
Related to [bsc#1093123](https://bugzilla.suse.com/show_bug.cgi?id=1093123).
=> Use the cache whenever something bad happens when refreshing the Pillar.

salt/_pillar/velum.py
Backport of #586 
When working on bsc#1093123 I've seen that the orchestration fails becasue 1) haproxy was temporarily down 2) the pillar cannot be accessed 3) `velum.py` crashes with an exception. We can avoid this failure for this kind of transient errors by using the Pillar cache (when present).
Related to [bsc#1093123](https://bugzilla.suse.com/show_bug.cgi?id=1093123).
=> [3.0] Use the cache whenever something bad happens when refreshing the Pillar.

salt/orch/kubernetes.sls
Backport of #588
* Do not set the `bootstrap_complete` flag in all the nodes: do it only in the nodes that had some role assigned.
This is important because, when some nodes are _unassigned_ and we bootstrap the cluster, those nodes will have the `bootstrap_complete` set anyway.
The problem appears when running the _node removal_ orchestration, as it uses that flag for prioritizing nodes when looking for a replacement (it tries to skip nodes with `bootstrap_complete` as it assumes that some role is already assigned and running in those machines).
* Remove the `bootstrap_in_progress` despite the result of the orchestration (as [we currently do in the node removal orchestration](https://github.com/kubic-project/salt/blob/master/salt/orch/removal.sls#L342-L351)... and we should do in the …
=> [3.0] Fix some orchestration flags

salt/orch/update.sls
Backport of #599 
To try to load a manifest in a 2.1 machine can lead to some unexpected problems: a crazy list of dependencies that can lead to some requisites that cannot be satisfied in a 2.1 machine...
So we will try to load the manifest in the first master that is upgraded to 3.x. If no masters are upgraded this time, we must assume they were upgraded in the past. Otherwise, upgrade will fail...
bsc#1096992
(cherry picked from commit ba205822e858d33a627e8717de4c1779d31f4c63)
=> [3.0] Try to load the manifests once we have at least one updated master.

salt/addons/init.sls, salt/addons/psp/init.sls, salt/cni/init.sls, salt/cni/update-post-reboot.sls, salt/orch/update.sls
Move the early services setup even before updating the masters (we can do this by removing some
unnecessary dependencies).
bsc#1096992
=> Move the early services setup before updating masters.

salt/crio/init.sls, salt/crypto/init.sls, salt/etcd/init.sls, salt/kube-apiserver/init.sls, salt/kube-controller-manager/init.sls, salt/kube-proxy/init.sls, salt/kube-scheduler/init.sls, salt/kubelet/init.sls, salt/kubernetes-common/init.sls, salt/reboot/init.sls
As discussed yesterday on irc, we should instruct salt to not install recommended packages.
=> Do not install recommends

salt/addons/dex/manifests/15-configmap.yaml
Goes together with changes from https://github.com/kubic-project/velum/pull/585
=> Add configmap from pillar data to dex ldap connectors

salt/orch/update.sls
=> Batch potentially dangerous and massive operations.

salt/kube-apiserver/apiserver.jinja
see https://github.com/kubernetes/kubernetes/pull/58968
k8s#1.11
=> [k8s 1.11] remove deprecated flag

pillar/params.sls, salt/_modules/caasp_etcd.py, salt/_states/caasp_etcd.py, salt/etcd/create-or-update-etcd-pillar.jinja, salt/etcd/etcdctl.conf.jinja, salt/etcd/migrate.sls, salt/orch/etcd-migrate.sls
upgrade#etcdctl
~~still untested and WIP~~ bootstrap was green :+1: locally
@mjura will look at the upgrade migration/orch  from 2 to 3
=> switch to etcd3 as a storage back-end

pillar/args.sls, salt/kube-apiserver/apiserver.jinja
Set things like the runtime config and admission control in the pillar. Minor cleanups.
feature#cleanups
=> Some configuration options in the API server

salt/haproxy/init.sls, salt/migrations/2-3/haproxy/init.sls
We could do the wait on the different places to avoid a generic piece
like haproxy having to wait for a specific component like the apiserver,
but we are already writing specific components in its configuration, and
a future reordering of states could trigger this error again.
So, when we kill haproxy, wait for it to be serving requests again before
continuing with the next state.
On the 2 to 3 upgrade this was causing a failure because right after
restarting haproxy we were trying to drain the node. Since we run this
operation on the very same machine that is being targeted, this `kubectl`
command cannot reach the apiserver (because haproxy is still initializing),
causing the whole update orchestration to fail.
Fixes: bsc#1109661
=> Always wait for haproxy to be serving requests before continuing

salt/haproxy/init.sls, salt/migrations/2-3/haproxy/init.sls
We could do the wait on the different places to avoid a generic piece
like haproxy having to wait for a specific component like the apiserver,
but we are already writing specific components in its configuration, and
a future reordering of states could trigger this error again.
So, when we kill haproxy, wait for it to be serving requests again before
continuing with the next state.
On the 2 to 3 upgrade this was causing a failure because right after
restarting haproxy we were trying to drain the node. Since we run this
operation on the very same machine that is being targeted, this `kubectl`
command cannot reach the apiserver (because haproxy is still initializing),
causing the whole update orchestration to fail.
Fixes: bsc#1109661
(cherry picked from commit …
=> [3.0] Always wait for haproxy to be serving requests before continuing

packaging/suse/make_spec.sh
Signed-off-by: Jordi Massaguer Pla <jmassaguerpla@suse.de>
=> use sle12sp3 images from suse registry

salt/addons/dex/manifests/20-deployment.yaml, salt/addons/dns/manifests/20-deployment.yaml, salt/haproxy/haproxy.yaml.jinja, salt/migrations/2-3/haproxy/haproxy.yaml.jinja
Signed-off-by: Vicente Zepeda Mas <vzepedamas@suse.com>
=> [3.0] Adds annotation to use docker/default seccomp profile (bsc#1099045)

pillar/certificates.sls, salt/kube-apiserver/apiserver.jinja, salt/kube-apiserver/init.sls
This PR configures the aggregation by adding a specific certificate and the required flags
Signed-off-by: Ludovic Cavajani <lcavajani@suse.com>
=> Configure aggregation layer (bsc#1108195)

salt/_modules/caasp_registry.py
Instead of using the `python` version to heuristically check if the image is running on `sle15`, use a file that is mapped from the host system into the containers.
This PR requires kubic-project/caasp-container-manifests#203 to be merged first.
Once these changes will be tested against `SLE15` based images, this PR is required as well: https://github.com/kubic-project/automation/pull/508.
Otherwise the tests will fail, because they are still expecting a `container-feeder.service` that is no longer present in our `SLE15` images.
=> Use the registry configuration mapped from the host node.

salt/kubelet/init.sls, salt/kubelet/kubelet-config.jinja, salt/kubelet/kubelet.jinja
(cherry picked from commit c02c3ec409576ec03b590d74cdf113106aa288e1)
https://github.com/kubic-project/salt/pull/621
https://github.com/kubic-project/caasp-container-manifests/pull/205
=> [3.0][bsc#1114645] Move deprecated flags to kubelet config.yaml

config/master.d/50-master.conf
=> Add a whitelist for returned events so we only save events that we care about

pillar/certificates.sls, salt/kube-apiserver/apiserver.jinja, salt/kube-apiserver/init.sls
This PR configures the aggregation by adding a specific certificate and the required flags
bsc#1108195 Aggregation layer needs configuration
Signed-off-by: Ludovic Cavajani <lcavajani@suse.com>
(cherry picked from commit 081d260d60a2e542af7418c026d9c55908abe10b)
rename aggregator to proxy-client
Signed-off-by: Ludovic Cavajani <lcavajani@suse.com>
(cherry picked from commit 641ab4ecda40061b734bdba42afbab7e4dc43b7e)
=> [3.0] configure aggregation layer, bsc#108195 

pillar/vars.sls, salt/_modules/caasp_txupdate.py, salt/_states/caasp_txupdate.py, salt/orch/kubernetes.sls, salt/orch/prepare-product-migration.sls, salt/orch/update.sls, salt/transactional-update/migration.sls
This orchestration will run transactional-update salt migration to change
the cluster to a new channel.
=> channel migration

salt/kubernetes-common/openstack-config.jinja
(cherry picked from commit 67e276cd10066918d7590d29d485215770795208)
=> [3.0] [CPI] Add self-signed certificate to CPI configuration, bsc#1101973

salt/kubernetes-common/openstack-config.jinja
(cherry picked from commit f93b74b9e7a77561c7e431f3a8c82667611da071)
=> [3.0] [CPI] Fix and remove empty lines in OpenStack cpi config, bsc#1101973 

salt/_modules/caasp_etcd.py
=> in python3 strings need to be decoded from binary objects

salt/etcd/etcdctl.conf.jinja
(cherry picked from commit 129466a842eea437639f13015d12341929d417d0)
Signed-off-by: Ludovic Cavajani <lcavajani@suse.com>
=> update etcdctl sysconfig with ENDPOINTS flag (bsc#1120047)

salt/kubelet/kubelet-config.jinja
=> Enable `ExperimentalCriticalPodAnnotation` feature gate in the kubelet

salt/cni/kube-flannel.yaml.jinja, salt/kubelet/kubelet.jinja
kubelet config and flannel config needed some tweak
=> [k8s 1.13] Adapt configs to 1.13

README.md
=> Added instructions for running unit tests

pillar/docker.sls, salt/docker/daemon.json.jinja
(cherry picked from commit b4c0474d0a141e4fc27b3b3e6de76288144a6e12)
=> [3.0] Add log rotation options to docker daemon (bug#1114832)

salt/kubernetes-common/openstack-config.jinja
(cherry picked from commit 9f8728a89ad3dc643b1ff7936e90e16f6d107ffe)
=> [3.0] [CPI] Sanitize the values from the pillar (bsc#1122439)

salt/_states/caasp_etcd.py
Cluster is to generic, use etcd cluster instead
=> Improve msg of healty function.

pillar/certificates.sls, salt/kube-apiserver/apiserver.jinja, salt/kube-apiserver/init.sls, salt/kubelet/kubelet-config.jinja
(cherry picked from commit's dd88fe82fa8a611db1593025b5c61818e7a61999 and 6309fb22ae122db6e2db2705fe47c1f4ae939ffb)
=> Disable anonymous access to Kubelet API (bsc#1121146)

salt/addons/dex/manifests/20-deployment.yaml, salt/addons/dns/manifests/20-deployment.yaml, salt/addons/tiller/manifests/20-deployment.yaml, salt/cni/cilium-ds.yaml.jinja, salt/cni/kube-flannel.yaml.jinja, salt/haproxy/haproxy.yaml.jinja
https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
bsc#1122783
=> [k8s 1.13][bsc#1122783] update critical pod configuration

salt/etcd/init.sls, salt/kube-apiserver/init.sls
This pr is fixing a failure in SLE15 for state when deploying cluster.
Increase timeout for ha-proxy so state doesn't fail
=> add minor changes for improving states robustness

pillar/cni.sls, salt/cni/cilium-ds.yaml.jinja
note: we dont have any caasp_registry for cilium yet. so this PR wont work now, until we have cilium in caasp_registry.
=> cilium: add repo for cilium

salt/_modules/caasp_orch.py
=> Make sure we refresh modules synchronously after syncing everything
