kubic-project/salt

salt/orch/kubernetes.sls

We need to refresh the pillar when running the orchestration, so we
make sure that if salt-master failed to connect to the database, it
will retry to do so and that we have the latest information
available.

Refresh pillar when running the orchestration

---

pillar/params.sls
salt/etcd-discovery/init.sls
salt/orch/kubernetes.sls
salt/reboot/init.sls
salt/top.sls

This is needed by rebootmgr in order to check the maximum amount on lock
holders.

reboot: added configuration for the lock holders

---

salt/docker/init.sls
salt/etcd/init.sls
salt/flannel/init.sls
salt/kubernetes-master/init.sls
salt/kubernetes-minion/init.sls

We have to include missing dependencies for state files
for docker
```
include:
- repositories
- flannel
```
for etcd, flannel, kube-master and kube-minion
```
include:
- repositories
```

Include missing dependencies for state files

---

salt/kubernetes-master/init.sls

Include something like `kubernetes.default.svc.cluster.local` in the DNS names in the API server certificate.

Add some extra names from the DNS domain

---

salt/docker/init.sls

For Kubernetes cluster docker iptables rules
are useless, we have to make sure to disable this.

Disable iptables created by docker

---

salt/etcd-proxy/etcd.conf
salt/etcd-proxy/init.sls

~~* adds a custom systemd unit file for etcd with a one line if statement that~~
~~checks to see if both member and proxy folders exist in /var/lib/etcd/ and~~
~~removes the member folder so that etcd members in proxy mode can start on next~~
~~reboot.~~
* adds a drop-in systemd unit file for etcd that adds an `ExecStartPre` clause removing the `member` directory if both `proxy` and `member` directories exist so that it can allow etcd to restart.
This does not affect etcd full members. It's also not possible to automatically
promote a proxy to member https://github.com/coreos/etcd/issues/2869#issuecomment-105607322
so this fix doesn't break any functionality.
~~* removes the extra parameters sent to etcd from the default systemd unit file,~~
~~since etcd picks up all the settings from the …

fix etcd proxy instance failure on restart

---

pillar/kube-minion.sls
salt/kubernetes-minion/kubelet.jinja

sles12/pause image only exists in caasp context.
This commit fixes it so that it works on opensuse

fix infra container image (=pause image) for opensuse

---

salt/ca/init.sls

With the YaST installation it's really straightforward to install the dashboard without a domain name. This makes the CA not to fail when there is not a domain name specified, we will just create the CA certificate anyway.

Do not set certificate `CN` if domain was not specified by a grain

---

salt/ca/init.sls

Even if no grains are set (because the domain could not be inferred), set the default dns domain from the pillar.
This ensures we also have a value for the `Common Name` value on the
certificate that will be generated for the Certificate Authority.

Always set `CN`

---

pillar/params.sls
salt/top.sls

For `kubectl proxy` to properly proxy to the Kubernetes dashboard, you
must run flanneld and docker on the master node. This will set up the
appropriate host routes.
Additionally, nodes cannot communicate with each other in host-gw mode
in flannel without modifying iptables rules to allow the traffic.
host-gw doesn't scale very well, due to needing to add a route to every
node for every node in the cluster. The iptables rules already allow the
flannel udp encapsulation port through (udp port 8285).

Bug 1032379 - Must install flanneld on the kubernetes master node

---

salt/kubernetes-minion/kubelet.jinja

Removes no longer valid --config flag, matches
kubic-project/terraform#32

Allow the kubelet to run on Kubernetes 1.6

---

salt/kubernetes-master/apiserver.jinja
salt/kubernetes-master/scheduler.jinja

Adds the leader-election flag to kube-scheduler (was already present on
kube-controller-manager)
Also sets the apiserver-count on kube-apiserver

Configure kube-{scheduler/controller-manager} leader elections

---

pillar/params.sls
salt/_modules/etcd_discovery_helpers.py
salt/etcd-discovery/init.sls
salt/orch/kubernetes.sls

Update the etcd role to dynamically choose the cluster size by default, using
the number of masters as the value. This dynamic value may still be overridden
by a pillar value.
We intentially don't make any attempts to prevent "invalid" cluster sizes here,
as doing so would cause issues during master addtion and removal (when that
becomes a suppored operation).

Update default etcd cluster size to match number of masters

---

salt/kubernetes-master/init.sls
salt/kubernetes-minion/kubeconfig.jinja
salt/kubernetes-minion/kubelet.jinja

This should fix [this trello issue](https://trello.com/c/yCbzToby).
Depends on #44 (rebased on top of it, where we define the local infrastructure domain).

Use a constant name for the API server

---

salt/hostname/init.sls
salt/motd/motd.jinja
salt/top.sls

This pulls in #44 as a dependency - this will go away when it is merged.

Set hostname on all nodes to match machine ID

---

salt/_modules/etcd_discovery_helpers.py

When etcd discovery is used, and the expected member count is larger
than the available pool of nodes, etcd will fail to start. So, we add
some logic to etcd_discovery_helpers to ensure we don't attempt to
form a cluster that is larger than the available pool of nodes.

Update etcd member count logic

---

config/master.d/api.conf
config/master.d/master.conf
config/master.d/peer.conf
config/master.d/reactor.conf
config/master.d/returner.conf
reactor/presence.sls

Moved from the `caasp-container-manifests` repo
Ideally all these config files should go into the `salt-master` docker image (as well as the Salt code, pillars, etc), but there is no problem in keeping the mounts in the manifests.
I have also included our first `reactor` action for presence of minions. It should be considered as an example more than really useful code...
Related to kubic-project/caasp-container-manifests#41

Config files for the Salt master from the caasp-container-manifests repo

---

pillar/params.sls
salt/docker/init.sls

This can be tested by deploying a cluster with [our Terraform scripts](https://github.com/kubic-project/terraform), doing:
1. `k8s-setup ... -Vpillar=proxy.http~http://something.com:8080,proxy.https~https://something.com:443` (requires kubic-project/terraform#66)
2. orchestrating the cluster
3. checking that, in any machine of the cluster, we can run `systemctl show --property=Environment docker` and get something like `Environment=HTTP_PROXY=http://something.com:8080`

Handle proxies in the docker daemon (bsc#1036627)

---

salt/etcd-proxy/etcd-proxy.conf.jinja

We have to remove IP based ETCD_INITIAL_ADVERTISE_PEER_URLS,
because they use HTTPS, which is failing for IP URLS with following error
```
health check for peer 100fbbb05571e58f could not connect: x509:
cannot validate certificate for 10.17.3.176 because it doesn't contain any IP SANs
```

Configure ETCD_INITIAL_ADVERTISE_PEER_URLS only with FQDN

---

salt/ca/init.sls
salt/cert/init.sls

For example, Norway country that we represent with its alpha-2 ISO
code will be `NO`, which will get translated when loading this YAML
into memory as False.
Force literal values and we avoid this problem.
Fixes: bsc#1039730

Certain key/values are interpreted in YAML and have special meaning

---

salt/etcd-proxy/etcd.conf

Stray + character was causing this line to not execute, and I ended up with a cluster with both folders present, preventing etcd from starting.

Fixing broken etcd configuration

---

pillar/params.sls
salt/etcd/init.sls
salt/kubernetes-minion/init.sls
salt/kubernetes-minion/kubelet.jinja

Minor changes in etcd and kubelet:
* do not remove `/var/lib/etcd`
* close some ports we don't really need for etcd, and open the port `10250` for `kubelet`.

Minor changes in etcd and kubelet

---

salt/cert/init.sls
salt/kubernetes-master/init.sls

Make cert always include `fqdn`
The only component that was adding `fqdn` to the list of dns names of SAN
certificates is the `kube-master` role.
However, depending on the size of the cluster and other possible reasons
it might happen that a etcd member falls in a `kube-minion` instance,
where the certificate is missing local ip addresses, as well as the `fqdn`
of the machine. With this change, we are enforcing `cert` to always
generate this information automatically, while we still allow to extend
it, in case that's still necessary (for example, as kubernetes-master still
requires).
Check https://bugzilla.novell.com/show_bug.cgi?id=1039269#c9 for further
information.
Fixes: bsc#1039269

Make cert always include `fqdn`

---

salt/reboot/init.sls

This triggers a chain reaction when the reboot sls is called
directly (salt-call state.apply reboot) on the last step of the
orchestration, since etcd-proxy includes etcd, and etcd includes
cert.
Cert sls will generate a new certificate overriding the current one
with all the correct DNS names and IP addresses, by one that only
contains `fqdn` as the only dns name.
Fixes: bsc#1040858

Do not include etcd-proxy on this last action

---

salt/docker/stop.sls
salt/etcd-proxy/stop.sls
salt/etcd/stop.sls
salt/flannel/stop.sls
salt/kubernetes-master/stop.sls
salt/kubernetes-minion/init.sls
salt/kubernetes-minion/stop.sls

Add a stop SLS for each service we wish to shutdown clearly, doing any
necessary pre-stop actions such as draining and cordoning kubelet.
There are few TODOs inline, any suggestions on the salt way to handle
these would be nice. I'm throwing this up now as it works enough to unblock
other parts of the upgrade, but I don't think it should be merged as-in. 
In the meantime, I'll go looking to see if there's a kubernetes module we can
use in place of shelling out to kubectl.

Allow for clean shutdown of nodes

---

pillar/fqdn.sls
salt/_modules/k8s_etcd.py
salt/cert/init.sls
salt/etcd-proxy/etcd-proxy.conf.jinja
salt/etcd/etcd.conf.jinja
salt/hostname/init.sls
salt/kubernetes-master/apiserver.jinja
salt/kubernetes-minion/init.sls
salt/kubernetes-minion/kubelet.jinja
salt/kubernetes-minion/stop.sls

The FQDN grain is unrelable, and depending on the node (and it's current
state) will give us different values. It's use needs to be dropped entirely,
Fixes bsc#1041951
Partially Fixes bsc#1041789

Don't rely on fqdn grain

---

salt/hostname/init.sls
salt/motd/motd.jinja

Operators don't want us to change the system hostname, which we previously
did to account for environments which don't provide unique DHCP hostnames.
We'll undo this change, as we have now removed our reliance on the system
default hostname.
Tested with:
* Unique + Resolvable Hostnames
* Unique + NOT Resolvable Hostnames
* NOT Unique + Resolvable Hostnames (hostname resolves to all 3 node IPs)
* NOT Unique + NOT Resolvable Hostnames
Fixes bsc#1041789

Don't change the system hostname

---

salt/ca-cert/init.sls
salt/ca/init.sls
salt/cert/init.sls
salt/docker/init.sls
salt/etcd-discovery/init.sls
salt/etcd/init.sls
salt/flannel-setup/init.sls
salt/kubernetes-master/init.sls
salt/kubernetes-minion/init.sls
salt/orch/kubernetes.sls
salt/reboot/init.sls
salt/top.sls

- Adapt some `cmd.run` to use `onchanges`, so they only execute when their
`watched` states change.
- Add `stateful: True` to some `cmd.run`s, so following the salt protocol
for this we ensure that the command didn't change anything in the system
state.
- Move `ca-cert` to its own SLS, so `cert` will only now generate the
`/etc/pki/minion.{key,crt}` files.
- The `cert` SLS will now be the only responsible for generating
certificates depending on the role of the machine. This way we ensure
that without mattering how this SLS is included it behaves in the same
way under all conditions. We might want to use a certificate for different
services, but that will need some extra changes.
- Change some `module.run` to `module.wait` so they only execute when the
`watched` states change.
- Remove …

Idempotent salt states

---

salt/orch/kubernetes.sls
salt/rebootmgr/init.sls

this will disable rebootmgr when orchestration starts.
@ereslibre @inercia PTAL.
not sure if i'm missing something.
Initially i wanted to define the service as part of the state (this is just a variation, i did a lot of them):
```
disable_rebootmgr:
salt.state:
- tgt: 'roles:kube-(master|minion)'
- service:
- name: rebootmgr
- running: False
- enabled: False
- reload: True
```
i think that defining a separate `role` just for this is stupid but i couldn't find any other way. suggestions are welcomed.

disable reboot manager when orchestration happens

---

salt/_grains/etcd_info.py

To maintaine etcd cluster configuration by salt,
it is needed to get etcd status about members and
their roles in etcd cluster. This etcd_info grain
module provides followind information:
- 'etcd_module' - return "available" if python-etcd 
module is installed
- 'members_all' - return list of all members in
etcd cluster
- 'member_type' - return role of local etcd service,
possible values "proxy", "member",
"leader"
- 'member_id' - return unique id of local etcd service
in the cluster
This grain module will be used by salt_delete state module
for removing etcd nodes from the cluster.
To run this module is required to install following packages:
- python-etcd
- python-urllib3
- python-dnspython

Add etcd_info salt grain module

---

pillar/params.sls
salt/cert/init.sls
salt/etcd-proxy/etcd-proxy.conf.jinja
salt/etcd/etcd.conf.jinja
salt/flannel-setup/init.sls
salt/flannel/flanneld.sysconfig.jinja
salt/kubernetes-master/addons/skydns-rc.yaml.jinja
salt/kubernetes-master/apiserver.jinja
salt/kubernetes-master/controller-manager.jinja
salt/kubernetes-minion/init.sls
salt/kubernetes-minion/kubeconfig.jinja

This change is enabling https for `etcd-proxy` and `flanneld` services and it is cleaning up pillar configuration for ssl

Enable https for all services and create dedicated ssl pillar profile

---

salt/kubernetes-minion/init.sls

Was missing a `]`, breaking a salt apply

Fixing broken build

---

pillar/params.sls
salt/cert/init.sls
salt/etcd-proxy/etcd-proxy.conf.jinja
salt/etcd/etcd.conf.jinja
salt/flannel-setup/init.sls
salt/flannel/flanneld.sysconfig.jinja
salt/kubernetes-master/addons/skydns-rc.yaml.jinja
salt/kubernetes-master/apiserver.jinja
salt/kubernetes-master/controller-manager.jinja
salt/kubernetes-minion/init.sls
salt/kubernetes-minion/kubeconfig.jinja

This PR reverts kubic-project/salt#86 because broke the daily image. Some code dealing with CA got rewritten in the meantime and this is causing issues.
Plus sometimes ago we agreed to put this code on hold and discuss whether we want that to be merged in time with the 1.0 release to avoid further bugs to be introduced.
@vrothberg: please keep an eye open on bugs, they might have been caused by the merge of kubic-project/salt#86

Revert "Enable https for all services and create dedicated ssl pillar profile"

---

salt/etcd/init.sls

This dir is created by the etcd rpm, and permissions
are maintained by etcd when it is running
The salt and etcd disagree an what these permissions are
causing extra "changed" entries. As etcd is changing
them to what it needs, and the directory is created
by etcd (and its RPM) we should not try and manage it.

Stop managing /var/lib/etcd in salt

---

config/master.d/returner.conf

This removes the hard coded password for salt.
Requires https://github.com/kubic-project/caasp-container-manifests/pull/46 to be merged.

Remove hardcoded secrets

---

salt/orch/kubernetes.sls

This allows more nodes to be deployed without causing
timeouts and failed runs on the `cert` state.
Also, remove concurrecny from the etcd member and proxy
to ensure members are created before proxies

Batch runs of the `cert` state

---

salt/orch/kubernetes.sls

The `ca` container was reporting this error during the orchestration:
```
service.dead	{
"__run_num__": 0,
"_stamp": "2017-06-12T10:33:29.009340",
"changes": {},
"comment": "State 'service.dead' was not found in SLS 'rebootmgr'\nReason: 'service' __virtual__ returned False: No service execution module loaded: check support for service management on SLES-12 \n",
"name": "rebootmgr",
"result": false,
"retcode": 2
}
```
Also, the overall result of the orchestration was not successfully (despite
individual highstates reported success) because of this. Containers don't
have `systemctl` available, so `salt` doesn't know how to handle this.
Right now, rely on our roles for doing this (despite we could have used
`virtual` grain -- but for some reason a container reports `physical`, which
doesn't …

Only run `service.dead` on salt minions that we know support it.

---

salt/orch/update.sls

We were using rebootmgr, but with that service disabled
we now need to use systemctl.
Salt has a bug where it will mark any call to `system.reboot` as
failed when a system actually reboots, so we cannot use the
built-in salt methods.
See saltstack/salt#24297 and saltstack/salt#31557

Change update orchestration to use systemctl

---

.gitignore
config/master.d/reactor.conf
pillar/beacons.sls
pillar/top.sls
reactor/README.md
reactor/etc-hosts.sls
reactor/presence.sls
salt/etcd-proxy/etcd-proxy.conf.jinja
salt/etcd/etcd.conf.jinja
salt/orch/kubernetes.sls
salt/orch/update-etc-hosts.sls

React to changes in IP addresses in minions by running an orchestration in the cluster for updating `/etc/hosts`.
It seems the Salt minion loses connectivity to the master when the IP address changes (as reported in saltstack/salt#41578), so the effect of this PR seems to be limited to the _change-IP-after-a-reboot_ case...
* start the cluster with TF  and run the orchestration
* identify the `dnsmasq` instance that is serving the network with "ps ax | grep dnsmasq" (for example, if your TF file uses the `caasp` prefix then you will see the `caaspnet` somewhere)
```
$ ps ax | grep dnsmasq
30038 ?        S      0:00 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/caaspnet.conf --leasefile-ro --dhcp-script=/usr/lib64/libvirt/libvirt_leaseshelper
30039 ?        S      0:00 …
```

React to IP addresses changes

---

pillar/params.sls
salt/top.sls
salt/transactional-update/10-increase-update-speed.conf.jinja
salt/transactional-update/10-update-rebootmgr-options.conf
salt/transactional-update/init.sls

This will ensure that the transactional-update code will
write a grain (`tx_update_reboot_needed:true`) on the
node instead of rebooting the node.
This also allows for increasing the frequency of the snapshots
being built

Update transactional-update to use "salt" option

---

salt/orch/kubernetes.sls
salt/orch/update-etc-hosts.sls
salt/orch/update.sls

Force a refresh of grains at the start of each orchestration run.

Refresh grains at the start of orchestration

---

salt/orch/kubernetes.sls

Salt's documentation calls this option out as dangerous, staging
that the state must be able to be ran concurrently. This is not
something we can reasonably ensure works, so lets not use it.
From Salt's documentation:
This flag is potentially dangerous. It is designed for use
when multiple state runs can safely be run at the same
time. Do not use this flag for performance optimization.

Remove concurrent=True from orchestrations

---

salt/orch/kubernetes.sls
salt/orch/update-etc-hosts.sls

This ensures that we do not run reactor orchestrations on
nodes that have not completed bootstrapping.
This ensures that a node cannot have 2 states applied to
it at the same time.

Ensure that reactor states only run on completed nodes

---

salt/kubernetes-minion/kubelet.jinja

Right now, caasp doesn't support kube-dns out of the box.
If customers wanted to have dns support, they have to bring it up on
their own by using `kubectl create -f kubedns.yaml`. But this will not
work until you add the cluster-dns and cluster-domain arguments to
kubelet args and restart the kubelet.
While doing this manually in every node is one pain point, salt will try
to bring it back to its original state. Meaning that the changes you
made to the kubelet args will no longer be there. So, unless you bring up
the caasp cluster with the addon set to true, you cannot have kube-dns
working reliably on the cluster.
This change will make it a little easier, by having these arguements by
default in every node.

Making the cluster-dns and cluster-domain arguments default

---

config/master.d/api.conf

Do not expose the salt-api to the entire world. This is needed only by Velum to trigger salt actions. Given both the containers use the same network namespace we can just bind this service to localhost.
By doing that we are going to reduce the attack surface.
This fixes one of the two issues reported by bsc#1043589
Note well: `interface` is not a valid option for salt-api, see [here](https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html).

salt-api: listen to localhost [bsc#1043589]

---

salt/orch/kubernetes.sls

This last step on the orchestration was returning a `False` result
because no targets were found to execute the grain set.
I can confirm before this change the orchestration returned 1 failed state, and after the change it returns success.

Add missing `tgt_type` so we target the minions we intend to

---

salt/orch/update-etc-hosts.sls

Currently, `update-etc-hosts` orchestration fails because `update_mine`
`salt.function` cannot target any minions at the beginning, and since
this is a prerequisite for other states, the Reactor orchestration
fails.
Only call to these `salt.function` if there are any minions to target.

Do not fail if `salt.function` has no minions to target

---

salt/etcd-discovery/init.sls

When adding new nodes, the `orch.kubernetes` orchestration was failing because
etcd is refusing to start since the etcd discovery mechanism was already used
when bootstrapping the cluster.
With this change we ensure that we use the discovery mechanism only when we
are boostrapping the cluster (no machines have the `bootstrap_complete` grain
set to true).
Required for the add nodes feature.

Do not run etcd discovery on every orchestration run, only the first time

---

pillar/params.sls
salt/proxy/init.sls
salt/top.sls

We will use the proxy settings system-wide when `pillar["proxy:systemwide"]` is set to `true` (enabled by default).
* invoke `k8s-setup` with `-Vpillar=proxy:http~http://error.com:8080,proxy:https~https://error.com:443`. This will add some additional Pillar values for setting the proxy.
* create the cluster
* orchestrate
* `ssh` into the machines and verify that `/etc/sysconfig/proxy` has the values we set in the Pillar
* from one of the master/minions, do `curl www.suse.com` and verify it fails (because the proxy is incorrect)
* from one of the master/minions, do `curl <dashboard-IP>` and verify it dumps the HTML code for the Dashboard.
* from one of the master/minions, do `docker pull alpine` and verify it fails.

Option for using the proxy settings system-wide (bsc#1036627)

---

config/master.d/master.conf

This works in conjunction with 
https://github.com/kubic-project/caasp-container-manifests/pull/62 and 
https://github.com/kubic-project/velum/pull/206
to allow explicit acceptance of nodes into salt.

Turn off `auto_accept`

---

salt/orch/update-etc-hosts.sls
salt/orch/update.sls

This ensure that the etc-hosts orchestration does not
run during an upgrade, as this can cause conflicts on
the nodes, which cause salt to fail to complete an
`orch.update` run.

bsc#1045381 Ensure updates do not conflict with etc-hosts

---

config/master.d/master.conf

When dealing with a large number of minions, timeouts are visible when
using the default value of 5 seconds. Increasing the CPU/RAM resources
allocated to the master helps, but given it it's short bursts of heavy usage
(bootstrap and upgrade), this shouldn't be necessary.
We increase the timeout from 5 to 20 seconds, allowing tasks to take longer
yet still succeed.

Increase salt-master timeout

---

salt/etc-hosts/hosts.jinja
salt/etc-hosts/init.sls
salt/orch/kubernetes.sls
salt/orch/update-etc-hosts.sls
salt/rebootmgr/init.sls
salt/top.sls
salt/transactional-update/init.sls

Render the /etc/hosts file on the admin node, so nodes are reacable via
their internal FQDNs everywhere. Additionally, include the admin node
in the /etc/hosts files. (bsc#1045186)
Once the system bootstraps, we now disable rebootmgr on the
admin node. This allows the velum initiated updates to takeover
and prevent any unexpected surprises. (bsc#1046602)
Adds the proxy setup to the admin node (bsc#1043538)

Apply select states to Admin node

---

salt/proxy/init.sls

YaST is also configuring proxy settings inside of `/root/.curlrc`, this is needed because zypper is using libcurl. So if you run zypper from a cronjob or `su`, the `/etc/sysconfig/proxy` variables are not parsed
and set in the environment. Which means, zypper will not use the proxy and fail. With `/root/.curlrc`, libcurl will use the proxies configured there.
Thanks to @thkukuk for the [explanation](https://github.com/kubic-project/velum/pull/214#issuecomment-311910779).

Handle curl proxy settings

---

salt/etcd/etcdctl.conf.jinja
salt/etcd/init.sls

Let's add /etc/sysconfig/etcdctl with paths to the client
server TLS files and endpoint. This will make possible to run
etcdctl command in easy way, e.g.
source /etc/sysconfig/etcdctl
etcdctl cluster-health

Define etcdctl config file with SSL variables

---

salt/kubectl-client-cert/init.sls
salt/top.sls

This certificate will be served by Velum when downloading the `kubeconfig`
file, and is specific for that usage.
Fixes: bsc#1046963

Add kubectl client certificate

---

salt/cert/init.sls

Add a specific dependency for the key to be present when generating
the certificate for the minion.

Add prerequisite for key to be present on `cert` sls

---

salt/docker/init.sls

Fix is easy so I didn't open bug for it.

Fix JINJA escaping for docker_opts in docker state module

---

salt/cert/init.sls

Since we added the minion certificate location to the pillar, also
take the public key location from the pillar, or the certificate
generation will fail if the pillar value changes.

When generating the certificate use the pillar path

---

config/master.d/master.conf

First of all, we can specify an external job cache. If we don't do that,
then the `keep_jobs` option only applies to the local cache. This means that
Salt will not clean up jobs, events and returns older than the specified
`keep_jobs` value (default: 24h) for the MySQL returner that we have already
configured.
Moreover, since we'd already be using MySQL as a job cache, we don't
have to use the local system (/var/cache/salt/master/jobs/) as a cache
(note that Salt would still be using this directory to avoid JID
collisions). The documentation also says that the local cache can be a
burden for large deployments.
See bsc#1044133

Set MySQL as the job cache for the Salt master

---

config/master.d/master.conf

This reverts commit de22c660a99bc1425295c86be7d7dc3e79089845 / https://github.com/kubic-project/salt/pull/132
For some reason, enabling this means devenv and CI is broken:
----------
ID: /etc/pki/minion.crt
Function: x509.certificate_managed
Result: False
Comment: An exception occurred in this state: Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/salt/state.py", line 1746, in call
**cdata['kwargs'])
File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1704, in wrapper
return f(*args, **kwargs)
File "/usr/lib/python2.7/site-packages/salt/states/x509.py", line 494, in certificate_managed
new = __salt__['x509.create_certificate'](testrun=True, **kwargs)
File "/usr/lib/python2.7/site-packages/salt/modules/x509.py", line 1374, in create_certificate …

Revert "Set MySQL as the job cache for the Salt master"

---

pillar/schedule.sls
pillar/top.sls

Salt's grains_refresh_every configuration param does not quite do
what we need it to, it's failing to refresh grains from the `grains`
file - leading to updates going undetected.
This change adds a slightly modified version of what this config
param internally does, adding the force_refresh: True argument,
ensuring we correctly refresh.
bsc#1048583

Ensure grains are always refreshed periodically

---

salt/ca/init.sls

This was a leftover from the previous implementation. Now the ca key
is present under `/etc/pki/private` in the ca container too (as it
mounts `/etc/pki`)

Fix `ca` key path

---

salt/orch/update.sls

Wait 1200 seconds (20 minutes) for minions to reboot, instead of the
default 300 seconds (5 minutes). We increase this to cover off cases
where slower to boot physical hardware is used.
20 minutes was chosen as, I've seen physical hardware take 10-12 minutes
in the past, and someone likely has something that is slower to reboot.
bsc#1048683

Upgrade: Wait longer for minions to reboot

---

salt/orch/kubernetes.sls

We will explicitly force all minions to refresh the mine after the `ca` minion has
published the `ca.crt` certificate on the mine, to avoid rendering problems with
later SLS being executed. It might happen that a minion was missing this information
on its mine, so the rendering of the SLS failed, effectively stopping the whole
orchestration process.
Fixes: bsc#1048548

Explicitly refresh the mine on all minions after the `ca` has published the `ca.crt`

---

salt/orch/update.sls

When we instruct a minion to reboot, we can't reliably
wait for the response from salt-minion letting us know
that the "systemctl reboot" command succeeded, as systemd
may choose to shutdown the salt-minion service before it
can sent out the "Yes, that worked" response.
Salt does not make any attempt to finish in progress
tasks when it receives a SIGTERM, leaving us with few
other viable choices for this.

Don't wait for minion responses when rebooting

---

salt/orch/update.sls

These additional requisites enforce a stricter ordering of tasks
during the upgrade. In some case, "-set-update-grain" would not
execute in the right place, potentially leading to a failed
upgrade.
bsc#1045381

Add extra requisites to the update orchestration

---

salt/orch/update.sls

Even with backgrounding the call, salt-minion sometimes still does not
have enough time to respond before systemd shuts down salt-minion on
some environments. By adding a 15 second delay, we give salt-minion
much more time than it should need in a healthy cluster to respond.
Additionally, switch from the deprecated syntax for supplying bg=True,
to the newer syntax which no longer logs a warning.
Followup up fix for bsc#1049200

Delay reboots during upgrade by 15 seconds

---

salt/kubernetes-master/init.sls

Wait for Kube-API to start and give a success to the /healthz endpoint before bringing up Kube-DNS, as otherwise we can run into an issue where the API extensions are not loaded.
See https://github.com/kubernetes/kubernetes/issues/47739 and it's resolving PR https://github.com/kubernetes/kubernetes/issues/49072

WIP: Wait for Kube-API before installing Kube-DNS

---

salt/kube-apiserver/apiserver.jinja

In our current configuration, kube-api logs a series of errors unless this is
set.

Kube-API: Set storage-backend to etcd2

---

config/master.d/master.conf

Salt's job cache is buggy, causing random failures to lookup mine data, which
in turn causes our deployments to fail.
Fixes bsc#1054256

Disable Salt's Job Cache

---

pillar/params.sls
salt/flannel-setup/config.json.jinja

Flannel was setup such that 150 workers could obtain a subnet before there
were not none left. By growing this range, and the size of the individual
allocations, we allow for up to 1024 workers with 510 pods on each.
bsc#1047847

Grow flannel CIDR to accommodate 1024 workers

---

salt/proxy/init.sls

It is ok to generate empty values in `/etc/sysconfig/proxy`, but `curl` does not like having an empty `--proxy` line and generates some warnings...

Do not generate an empty --proxy line in curlrc

---

salt/addons/init.sls
salt/kube-apiserver/init.sls

Wait for the API server port after starting the service. So we can just `require: kube-apiserver` for invoking  `kubectl` safely...

Wait for the API server after starting the service

---

salt/_modules/k8s_etcd.py

If we had enough masters to form a etcd cluster, we would end up returning
"None" from this method, preventing the cluster formation.

Ensure k8s_etcd.get_cluster_size works for multi-master

---

pillar/params.sls
salt/etc-hosts/hosts.jinja
salt/haproxy/haproxy.cfg.jinja
salt/haproxy/haproxy.manifest
salt/haproxy/init.sls
salt/kube-apiserver/apiserver.jinja
salt/kube-apiserver/init.sls
salt/top.sls

Now that we can have multiple masters, we need a way for the various
services and end-users to be load balanced over the set of kube-api
servers.
We install haproxy on each node, inside a docker container, configured
to load balance requests over all the cluster masters. This haproxy
is configured to listen on 0.0.0.0 on the masters, and 127.0.0.1 on
the workers.
This is to allow the minions to simply "talk" to 127.0.0.0, and be
routed to an active kube-api server.

Use haproxy to load balance Kube API requests

---

pillar/params.sls
salt/kube-apiserver/apiserver.jinja

Parametrize Kubernetes apiserver storage backend. This will be used
in future for migration process from storage etcd2 to etcd3.

Set kube-apiserver storage backend as option

---

salt/flannel/flanneld.sysconfig.jinja

Flannel in 0.8.0 rejects the "-logtostderr" flag we were providing, this
doesn't seem to have ever been an option, however it was silently ignored
in the past.

Fix flannel config for 0.8.0

---

salt/etc-hosts/hosts.jinja

The short hostname for masters was not being set, as it was for both
the admin node, and worker nodes
Fixes bsc#1057794

Include short hostname for masters

---

salt/docker/init.sls
salt/etcd/init.sls
salt/transactional-update/init.sls

Ensure systemd is reloaded as soon as a unit is changed, rather than relying
on a task later within the orchestration to execute.
Fixes bsc#1057641

Ensure systemd is reloaded after units are changed

---

salt/etc-hosts/hosts.jinja

This was added to ensure Dex was always reachable, however, with multi masters,
this name was assigned to 3 different lines in /etc/hosts. Most consumers of
/etc/hosts do not deal with this as they would a round-robin DNS entry which
returns multiple IPs.
When the "selected" master is powered off, this name continues to resolve
the same dead IP address. As Dex uses a NodePort service, putting this to
127.0.0.1 works as we expect it to.

Move External FQDN to 127.0.0.1 address

---

pillar/params.sls

Depends on: https://github.com/kubic-project/velum/pull/303

Set etcd3 as default backend storage

---

salt/addons/init.sls

Tiller requires a cluster role binding to work correctly with the new
RBAC changes. Add this cluster role binding so that helm commands work
correctly.

Add cluster role binding for tiller

---

pillar/params.sls
salt/addons/addons/kubedns-sa.yaml
salt/dex/dex.yaml
salt/dex/init.sls
salt/dex/roles.yaml

LDAP password is now generated when admin node starts, and LDAP parameters are passed via the pillar during bootstrap.

Removing hardcoded LDAP admin password

---

salt/etcd/create-or-update-etcd-pillar
salt/etcd/migrate.sls
salt/orch/etcd-migrate.sls

In Kubernetes v1.7 default storage backend for apiserver is 'etcd3'.
We need orchestrate migration between version 'etcd2' and 'etcd3'.
To migrate etcd storage version we have to execute following command on Admin node:
```
docker exec -ti $(docker ps | grep salt-master | cut -d" " -f1) salt-run state.orchestrate orch.etcd-migrate
```
For testing please do following steps:
1. Deploy and bootstrap CaaSP2.0 Beta 1 version
2. On Admin node please remount filesystem as RW
```
btrfs property set -ts /.snapshots/1/snapshot ro false
mount -o remount,rw /
```
3. Copy on Admin node etcd/migrate.sls, etcd/create-or-update-etcd-pillar and orch/etcd-migrate.sls to /usr/share/salt/kubernetes/salt/
```
cp etcd/migrate.sls /usr/share/salt/kubernetes/salt/etcd/
cp etcd/create-or-update-etcd-pillar …
```

Add orchestration for etcd storage 'etcd2' to 'etcd3'

---

salt/dex/init.sls

Without this, We're seeing an error post-bootstrap, so deployments
look green, but fail with:
The following requisites were not found:
require:
id: kube-apiserver

Include kube-apiserver in the dex role

---

salt/dex/dex.yaml

The SLES based dex container does not put dex in /usr/local/bin
Part of bsc#1058833

Update paths to match SLES based Dex container

---

pillar/params.sls

This is set only from Velum, so we should not fail when we orchestrate things with Salt

Set a default external fqdn in the pillar

---

salt/orch/kubernetes.sls
salt/orch/update-etc-hosts.sls

Fix another case where the etc hosts update orchestration would otherwise
conflict with the bootstrap / add node orchestration.
bsc#1059577

Prevent update-etc-hosts conflicting with bootstrap

---

salt/_states/caasp_service.py
salt/etcd/init.sls

This new state will allow us to make sure that a service is running
in a stable manner. Also, will do some waits in case systemd will
do retries on the background, what avoids instant failure from salt
being reported with a regular `service.running`.
Fixes: bsc#1059105

Add `caasp_service.running_stable`

---

salt/dex/dex.yaml

This will make it so that Dex will be happy to redirect you to velum

Add a URL off Velum as a valid OIDC redirect URI

---

salt/kube-apiserver/apiserver.jinja

Remove duplicated storage-backend option for API server configuration
Option storage-backend is provided two times for API server configuration.
We have to keep only one with value provided from pillar.

Remove duplicated storage-backend option for API server configuration, bsc#1061810

---

pillar/params.sls
salt/dex/ensure-dex-running.sls
salt/orch/kubernetes.sls

We shouldn't allow a bootstrap to complete without Dex being up and
running, so lets wait for the Dex API to start responding.

Dex: Wait for Dex to be fully up and running

---

salt/kube-apiserver/apiserver.jinja

Option storage-backend is provided two times for Kubernetes API configuration.
We have to keep only one option with value provided from pillar.
(cherry picked from commit c4b42e689a0044a73715ff9e3619f709b3bca982)
Backport of https://github.com/kubic-project/salt/pull/240

[2.0] Remove duplicated storage-backend option for Kubernetes API, bsc#1061810

---

pillar/params.sls
salt/kubernetes-common/openstack-config.jinja

We would like add new pillar value floating, which will be used to configure floating network
for cloud provider intergration with OpenStack. If this option is specified, it will create floating ip
for loadbalancer automatically.

Add floating network to cloud-provider integration with OpenStack

---

salt/addons/addons/tiller.yaml.jinja

Currently the tiller image being used for the tiller deployment is
from the upstream registry at gcr.io. We should be using the SLES
based docker image instead of the upstream one.
Fixes: bsc#1062380

Update tiller deployment to use sles-based docker image

---

pillar/vars.sls
salt/dex/dex.yaml

Some scenarios where the admin node's private IP is not accessible
to the outside world require that we use a end user provided FQDN
- e.g. as is the case on OpenStack and possibly other cloud
environments. Allow redirections to this FQDN.
Part of bsc#1062291
Depends-On: https://github.com/kubic-project/velum/pull/322
Depends-On: https://github.com/kubic-project/automation/pull/164

Allow Dex to redirect to the Dashboard's external FQDN

---

pillar/vars.sls
salt/dex/dex.yaml

Some scenarios where the admin node's private IP is not accessible
to the outside world require that we use a end user provided FQDN
- e.g. as is the case on OpenStack and possibly other cloud
environments. Allow redirections to this FQDN.
Part of bsc#1062291
Backport of https://github.com/kubic-project/salt/pull/251

[2.0] Allow Dex to redirect to the Dashboard's external FQDN

---

salt/kube-apiserver/apiserver.jinja

With the default value (protobuf), the kubernetes api server will sit
in a (slow) restart loop when multimaster is enabled, logging a stacktrace
and then restarting. This will manifest as, most commonly, "Unable to
connect to the server: unexpected EOF" from kubectl. This will break
bootstrap as we need to talk to K8S API to deploy dex, kube-dns, and
tiller.
bsc#1063235
bsc#1063285
bsc#1063543

Revert K8S to a storage media type of json

---

salt/kube-apiserver/apiserver.jinja

With the default value (protobuf), the kubernetes api server will sit
in a (slow) restart loop when multimaster is enabled, logging a stacktrace
and then restarting. This will manifest as, most commonly, "Unable to
connect to the server: unexpected EOF" from kubectl. This will break
bootstrap as we need to talk to K8S API to deploy dex, kube-dns, and
tiller.
bsc#1063235
bsc#1063285
bsc#1063543

[2.0] Revert K8S to a storage media type of json

---

pillar/params.sls

With etcd3, the kubernetes api server will sit in a (slow) restart loop
when multimaster is enabled, logging a stacktrace and then restarting.
This will manifest as, most commonly, "Unable to connect to the server:
unexpected EOF" from kubectl. This will break bootstrap as we need to
talk to K8S API to deploy dex, kube-dns, and tiller.
bsc#1063235
bsc#1063285
bsc#1063543

Revert K8S to use etcd2 storage format

---

pillar/params.sls

With etcd3, the kubernetes api server will sit in a (slow) restart loop
when multimaster is enabled, logging a stacktrace and then restarting.
This will manifest as, most commonly, "Unable to connect to the server:
unexpected EOF" from kubectl. This will break bootstrap as we need to
talk to K8S API to deploy dex, kube-dns, and tiller.
bsc#1063235
bsc#1063285
bsc#1063543
Backport of https://github.com/kubic-project/salt/pull/262

[2.0] Revert K8S to use etcd2 storage format

---

salt/haproxy/haproxy.cfg.jinja
salt/top.sls

Velum to get kubeconfig connects to Dex service on kube-masters nodes.
For multimaster configuration it needs haproxy installed because all Kube-API
domains will be binded to localhost 127.0.0.1

Allow to deploy haproxy pod on Admin node, bsc#1062728

---

salt/haproxy/haproxy.cfg.jinja
salt/top.sls

Velum to get kubeconfig connects to Dex service on kube-masters nodes.
For multimaster configuration it needs haproxy installed because all Kube-API
domains will be binded to localhost 127.0.0.1
(cherry picked from commit 7ef721b6bc61a5c6c20e1a027ef18aa2507ffc16)

[2.0] Allow to deploy haproxy pod on Admin node, bsc#1062728

---

salt/docker/init.sls

Update salt to reference the new docker package name, as this was renamed
from "docker" to "docker_1_12_6"

Docker package was renamed to docker_1_12_6

---

salt/etc-hosts/init.sls

We would like to keep /etc/hosts file updated for velum-dashboard with
Admin host. Velum needs to know external name of Kube API which will be used
to register in Dex service. Problem was discovered and discribed in bug 1062728

Keep updated /etc/hosts on velum-dashboard container, bsc#1062728

---

salt/etc-hosts/init.sls

We would like to keep /etc/hosts file updated for velum-dashboard with
Admin host. Velum needs to know external name of Kube API which will be used
to register in Dex service. Problem was discovered and discribed in bug 1062728
Backport of https://github.com/kubic-project/salt/pull/269

[2.0] Keep updated /etc/hosts on velum-dashboard container, bsc#1062728

---

pillar/params.sls
salt/top.sls
salt/velum/init.sls

This ensures that the dashboard_external_fqdn is registered within
the velum TLS certificate.
bsc#1063998

Manage the Velum TLS cert

---

pillar/params.sls
salt/top.sls
salt/velum/init.sls

This ensures that the dashboard_external_fqdn is registered within
the velum TLS certificate.
bsc#1063998
Backport of https://github.com/kubic-project/salt/pull/271

[2.0] Manage the Velum TLS cert

---

salt/etcd/etcdctl.conf.jinja

Quick tip about how to source the variables defined inside of the file to quickly have etcdctl work.
I always find myself copy&pasting the contents of this file to `--flag-xyz`, sourcing the file is much more convenient but you have to know about `set -a`.

Add help message to etc/sysconfig/etcdctl

---

salt/_modules/caasp_filters.py
salt/velum/init.sls

Ensure we correctly handle FQDN values for the `dashboard` pillar when
generating the Velum TLS certificate.
Fixes bsc#1064284

Correctly handle FQDN `dashboard` values in Velum cert

---

salt/_modules/caasp_filters.py
salt/velum/init.sls

Ensure we correctly handle FQDN values for the `dashboard` pillar when
generating the Velum TLS certificate.
Fixes bsc#1064284
Backport of https://github.com/kubic-project/salt/pull/274

[2.0] Correctly handle FQDN `dashboard` values in Velum cert

---

salt/_states/caasp_cmd.py
salt/_states/caasp_service.py
salt/addons/init.sls
salt/dex/init.sls

This state module will provide `run` state with `retry` option that
accepts `attempts` and `interval` arguments. This allow us to retry a command
if it failed, and retry to this maximum number of retries, sleeping
between retries.

Add `caasp_cmd` state module featuring `run` with retry feature

---

salt/velum/init.sls

It was backported from https://github.com/kubic-project/salt/pull/282

[2.0] Synchronize /etc/hosts on velum after container restarts, bsc#1062728

---

pillar/params.sls
salt/etcd-discovery/init.sls
salt/etcd/init.sls
salt/flannel-setup/init.sls
salt/flannel/flanneld.sysconfig.jinja
salt/flannel/init.sls
salt/kube-apiserver/apiserver.jinja
salt/reboot/init.sls

Wait for `etcd` to be alive before trying to set anything
Remove the 'ssl:enabled' pillar: we do not really support non-SSL deployments...

Wait for etcd to be alive

---

salt/_states/caasp_cmd.py
salt/dex/init.sls
salt/kubelet/init.sls

New `retry['until']` argument for `caasp_cmd.run`
Use a `unless/onlyif` and `retry['until']` for skipping some executions and not using some nasty loops

Remove some nasty loops

---

salt/_states/caasp_retriable.py
salt/etcd/init.sls
salt/flannel/init.sls
salt/haproxy/init.sls
salt/kube-apiserver/init.sls
salt/kubelet/init.sls

This is an attempt to fix bsc#1064186 by executing the iptables statements more than once.
This PR introcuces also `caasp_retriable.retry` state that allows to retry any kind of salt state. Once merged we could get rid of the `caasp_cmd`.

Fix random iptables crashes bsc 1064186

---

salt/orch/update.sls

This is the safest path, but a refactor should come to make this part
of the ca highstate so the update and the kubernetes orchestrations
just force the ca highstate on both cases.
Related: bsc#1066653

Generate sa key in the update orchestration

---

salt/container-feeder/init.sls
salt/container-feeder/stop.sls
salt/orch/update.sls

This will allow us to control when container-feeder starts to load new
images from the filesystem. Due to some possible docker configuration changes
it might be restarted while container-feeder is working (if we keep it
enabled). Force to disable the service before rebooting.
Fixes: bsc#1066653

Disable container-feeder before rebooting

---

salt/etc-hosts/hosts.jinja

also explain in a comment why we need to set the apiserver for 127.0.0.1
on all hosts
(bsc#1067219)
(cherry picked from commit 610f65e57c7daa96d9f7ad51addcb0e919fba837)
Backport of https://github.com/kubic-project/salt/pull/302

[2.0] only set service entries for localhost on kube-master

---

pillar/certificates.sls
salt/ldap/init.sls
salt/top.sls

Since Dex will connect to LDAP using this FQDN/IP, make sure that the
TLS handshake will succeed by regenerating the certificate early in
the orchestration, so it includes this FQDN/IP in the SAN extensions
of the LDAP certificate.
Fixes: bsc#1069175

Include `Internal Dashboard FQDN/IP` value in the LDAP certificate

---

salt/etc-hosts/hosts.jinja

Currently, we assumed external names were FQDNs. When an IP was used instead,
we would generate an incorrect /etc/hosts.
bsc#1070154

Support IPs as Kube external FQDN in /etc/hosts

---

salt/docker/init.sls
salt/proxy/init.sls

Instead, we write an empty string, because we don't intend to write
`None` on the configuration file.

Never write `None` if we get `null` on the pillar override

---

salt/_macros/certs.jinja
salt/cert/init.sls
salt/dex/init.sls
salt/kube-apiserver/init.sls
salt/kube-proxy/init.sls
salt/kubectl-config/init.sls
salt/kubelet/init.sls
salt/ldap/init.sls
salt/velum/init.sls

In the certs macros, do not assume _"names"_ are always names and _"ips"_ are always IPs: just filter with the `is_ip()` filter and act accordingly.
Fix certifcates for dex: there were entries like `DNS:DNS:dex`
Minor shortcuts in the arguments.
Fixes: bsc#1069205

Fix certificates (bsc#1069205)

---

salt/orch/update-etc-hosts.sls

The final state in the etc-hosts orch was not actually calling
anything, and hasn't been for quite a while. Lets remove it, so
that the error it logs can be finally be gone!

Remove empty state from etc-hosts orch

---

salt/_macros/certs.jinja
salt/_modules/caasp_pillar.py
salt/addons/dns/init.sls
salt/addons/tiller/init.sls
salt/docker/init.sls
salt/etcd-discovery/init.sls
salt/flannel-setup/config.json.jinja
salt/kube-apiserver/apiserver.jinja
salt/kube-controller-manager/controller-manager.jinja
salt/kube-scheduler/scheduler.jinja
salt/kubelet/init.sls
salt/kubelet/kubelet.jinja
salt/ldap/init.sls
salt/proxy/init.sls
salt/velum/init.sls

if `pillar[x]` can return `None`, we can get a nasty `"None"` string when replacing `{{pillar[x]}}` in a Jinja template. And, in general, `None`s are rather annoying in Salt/Jinja...
So this PR implements our own version of `pillar.get` that sanitizes the output, never returning `None` and converting `"true"`/`"false"` to `True`/`False`.

Use a sanitized version of pillar.get

---

pillar/params.sls
salt/_macros/certs.jinja
salt/cert/cert-bundle.jinja
salt/cert/init.sls
salt/dex/init.sls
salt/kube-apiserver/init.sls
salt/kube-proxy/init.sls
salt/kubectl-config/init.sls
salt/kubelet/init.sls
salt/ldap/init.sls
salt/velum/init.sls

In the certs macros, do not assume "names" are always names and "ips" are always IPs: just filter with the "is_ip" filter.
Minor shortcuts in the arguments.
Fixes: bsc#1069205
Backport to 2.0 of https://github.com/kubic-project/salt/pull/311

[2.0] Fix certificates

---

config/master.d/50-reactor.conf
pillar/beacons.sls
salt/_beacons/default_network_interface_settings.py

Fixes: bsc#1063709
Backport of https://github.com/kubic-project/salt/pull/331

[2.0]  Add beacon to notify network changes only on the default network interface

---

salt/_macros/kubectl.jinja
salt/kubelet/init.sls
salt/kubelet/stop.sls

Do not try to pass the kubeconfig in the `KUBECONFIG` env var: it can be problematic. Just use the `--kubeconfig` argument of `kubectl`

Explicitly pass the kubeconfig file to kubectl

---

salt/kubelet/init.sls

The `onlyif` section can fail its check (without retrial opportunity), making
the whole uncordon process to abort, when we really want to uncordon a node.
In the future, we need to keep track of cordoned nodes by the update so we
only uncordon those, leaving cordoned the nodes that were cordoned by the user.
In any case, for this issue, `kubectl` will be smart enough:
- For a cordoned node, uncordoning:
```
~ KUBECONFIG=~/Downloads/kubeconfig kubectl uncordon 7a4f4985eaed4f519e27900ece559b8e.infra.caasp.local
node "7a4f4985eaed4f519e27900ece559b8e.infra.caasp.local" uncordoned
~ echo $?
0
```
- For an uncordoned node, uncordoning again:
```
~ KUBECONFIG=~/Downloads/kubeconfig kubectl uncordon 7a4f4985eaed4f519e27900ece559b8e.infra.caasp.local
node …
```

Do not check if we need to uncordon this node depending on its state.

---

pillar/params.sls
salt/flannel-setup/config.json.jinja

`SubnetMin` and `SubnetMax` specify the first and last subnets that will be assigned to nodes in the cluster. Given the network CIDR, Flannel can calculate both automatically. Do not specify these parameters except when users really know wheta they are doing.
Anyway, I think both parameters will disappear once we move to CNI, as the kubernetes subnets manager is responsible for these things...

Let flannel auto-calculate the Max and Min subnet

---

salt/kubelet/init.sls
salt/kubelet/stop.sls

Fix kubelet highstate to uncordon the node only if we did cordon it by
one of our processes (like an update).
Without this patch, adding new nodes or performing an update would
uncordon all nodes unconditionally, without taking into account if a
user had a node cordoned for some reason (e.g. hardware failures or
other reasons). Do not uncordon those nodes, keep them cordoned.
Fixes: bsc#1050017

Only uncordon nodes that were cordoned because of our own processes

---

salt/_macros/certs.jinja

As the discovered IP addresses are not static, that we don't maintain that
the certs are updated+services are reloaded upon IP change, that we're
including all IPs - even 127.0.0.1 - in this list, and that we don't make use
of any of these SAN's, we should remove them.

Remove discovered IP addresses from certs

---

config/master.d/50-master.conf
salt/_modules/caasp_etcd.py
salt/_modules/caasp_filters.py
salt/orch/kubernetes.sls

Use a batch size for etcd setup equal to the number of etcd masters
Minor cleanups and a fix for a case where `caasp_etcd.py` could return 0.
See https://bugzilla.suse.com/show_bug.cgi?id=1066695

Use a batch size for etcd setup equal to the number of etcd masters (bsc#1066695)

---

pillar/args.sls
pillar/docker.sls
pillar/registries.sls
pillar/top.sls
salt/_modules/caasp_docker.py
salt/docker/daemon.json.jinja
salt/docker/init.sls
salt/proxy/init.sls

(This is basically #119 revamped, and prepared for insecure registries as implemented in #129)
A new pillar structure is introduced where registroes can be specified in the followig way:
```yaml
registries:
- url: my-reg1.com:5000
- url: my-reg2.com:5000
cert: |
- url: some.registry.com:5000
mirrors:
- url: http://local.mirror.lan:5000
cert: |
```
I've followed the instruction found [here](https://docs.docker.com/registry/insecure/#using-self-signed-certificates) for adding customers' certificates to Docker so they can pull from other registries.
* download [the caaspctl script](https://raw.githubusercontent.com/inercia/caasp-tf/master/resources/common/caaspctl) and copy it to `/root` in the Admin Node
* `ssh admin-node` and `./caaspctl registry certs` and `./caaspctl registry start`. …

Registries and mirrors (bsc#1039877)

---

salt/swap/init.sls
salt/top.sls

Unmount existing swaps; comment out swaps from fstab file.
No changes to swap partitions on disk. No reboot required.

Add swap disabling

---

pillar/args.sls
pillar/docker.sls
pillar/registries.sls
pillar/top.sls
salt/_modules/caasp_docker.py
salt/docker/daemon.json.jinja
salt/docker/init.sls

Use the `suse_registry_mirror:url` and `suse_registry_mirror:cert` until we fully support the `regiestries` data structure in 2.0, so this is a pseudo-backport of #313

[2.0] (pseudo-)backport of #313 for using the SUSE registry mirror

---

salt/addons/tiller/tiller.yaml.jinja

Update the salt template for the tiller deployment to install the
sles12/tiller:2.7.2 container image which is the latest version for
this image.

Update salt to use 2.7.2 version of tiller

---

salt/_macros/certs.jinja
salt/dex/init.sls
salt/kube-apiserver/init.sls
salt/kube-controller-manager/init.sls
salt/kube-scheduler/init.sls
salt/ldap/init.sls
salt/velum/init.sls

This will make the certificate request to the CA more resilient to
transient errors, in case of overload or any other reasons that make
the CA slow when creating new requested certificates.
Fixes CI.
Fixes: bsc#1070989
Backport of https://github.com/kubic-project/salt/pull/359

Retry certificate generation

---

salt/cni/update-post-start-services.sls

Between minor updates on 3.x we can get a bad timing when removing the
flannel.1 interface as the DaemonSet will start right after the worker
reboot, and we could remove the interface when flannel thinks it exists
and it goes to add arp entries to it, leading to a failure and to an
invalid kubernetes networking status.

Do not remove flannel interface when updating 3.x

---

salt/_states/caasp_retriable.py
salt/kube-controller-manager/init.sls
salt/kube-proxy/init.sls
salt/kube-scheduler/init.sls
salt/kubelet/init.sls
salt/orch/update-etc-hosts.sls
salt/orch/update.sls

This will allow us to reduce the timeframe in which the update-etc-hosts
orchestration can pop up, eventually running states on minions effectively
taking their lock and making this orchestration fail. We don't want the
update-etc-hosts orchestration to interfere with the main update
orchestration.
We'll release minion per minion grain when they are done, but let's
block all of them at the very beginning.
Fixes: bsc#1077086
Backport of https://github.com/kubic-project/salt/pull/354

Early mark nodes requiring update reboot as update in progress.

---

salt/_states/caasp_retriable.py
salt/kube-controller-manager/init.sls
salt/kube-proxy/init.sls
salt/kube-scheduler/init.sls
salt/kubelet/init.sls

Explicitly wait for `caasp_retriable` states.
Fixes CI.
Fixes: bsc#1070989
Backport of https://github.com/kubic-project/salt/pull/362

Catch any exceptions on `caasp_retriable` state, and treat it as a regular failure

---

salt/swap/init.sls
salt/top.sls

Unmount existing swaps; comment out swaps from fstab file.
No changes to swap partitions on disk. No reboot required.
Backport of https://github.com/kubic-project/salt/pull/345

[2.0] Add swap disabling

---

salt/dex/dex.yaml

See https://build.suse.de/request/show/153621 and https://build.opensuse.org/package/rdiff/devel:CaaSP:Head:ControllerNode/caasp-dex?linkrev=base&rev=7

Update dex binary name to caasp-dex

---

pillar/fqdn.sls
pillar/mine.sls
pillar/top.sls
salt/_macros/certs.jinja
salt/_modules/caasp_net.py
salt/cert/init.sls
salt/cni/update-pre-orchestration.sh
salt/cni/update-pre-orchestration.sls
salt/etc-hosts/hosts.jinja
salt/etcd/etcd.conf.jinja
salt/etcd/etcdctl.conf.jinja
salt/etcd/init.sls
salt/haproxy/haproxy.cfg.jinja
salt/hostname/init.sls
salt/kube-apiserver/apiserver.jinja
salt/kube-apiserver/init.sls
salt/kube-proxy/proxy.jinja
salt/kubelet/init.sls
salt/kubelet/kubelet.jinja
salt/kubelet/stop.sls
salt/kubelet/update-post-start-services.sls
salt/kubelet/update-pre-orchestration.sh
salt/kubelet/update-pre-orchestration.sls
salt/ldap/init.sls
salt/motd/motd.jinja
salt/orch/kubernetes.sls
salt/orch/update-etc-hosts.sls
salt/orch/update.sls
salt/top.sls
salt/velum/init.sls

With CaaSP 3.0, we're introducing a requirement for machines to have valid+unique hostnames in order to allow for the K8S CPIs to function correctly.
This means our generated hostname is no longer needed, as our environment requirements force operators to provision servers with unique hostnames.
TODO:
Some decisions made:
1. Continue to use /etc/hosts - don't rely on external name servers. This can be revisited later, but keeps the change smaller and less likely to break
2. Prefer to use short-form hostnames rather than FQDNs.
3. Keep the machine-id /etc/hosts entries for now as I suspect this will ease rolling upgrade.
4. Keep the machine-id entries in certs for now as I suspect this will ease rolling upgrade.
5. Make the minimal changes needed for CPIs to work as a first step …

No longer use machine-id's as node names

---

salt/cni/update-pre-reboot.sls
salt/orch/kubernetes.sls
salt/orch/update.sls

Use the same code convention for ids in the orchestration as all the other ids.
Cleanup some files when updating CNI.

Minor cleanups in orchestrations

---

salt/cni/update-pre-reboot.sls

When updating the cluster, do not try to remove some _flannel_ file that cannot be removed, and remove some other instead

Do not try to remove some file in a read-only dir

---

salt/_macros/kubectl.jinja
salt/addons/tiller/init.sls
salt/addons/tiller/tiller.yaml.jinja

The helm client looks for a tiller deployment called 'tiller-deploy' to
establish if tiller is already installed in the cluster, or not. Update
our salt install of tiller to use a deployment with the same name so
that it will be recognized by the helm client as already being
installed.
Fixes: bsc#1066201

helm should detect salt-installed tiller service

---

salt/addons/dns/kubedns.yaml.jinja
salt/addons/tiller/tiller.yaml.jinja
salt/cni/kube-flannel-rbac.yaml.jinja
salt/cni/kube-flannel.yaml.jinja
salt/dex/dex.yaml
salt/dex/roles.yaml

* [rbac has been promoted to stable](https://v1-8.docs.kubernetes.io/docs/admin/authorization/rbac/)
* [deployment is now v1beta2](https://v1-8.docs.kubernetes.io/docs/concepts/workloads/controllers/deployment/)
* [deamonset is now v1beta2](https://v1-8.docs.kubernetes.io/docs/concepts/workloads/controllers/daemonset/)

Update our manifests to reflect kubernetes 1.8 changes

---

salt/addons/dns/init.sls
salt/addons/dns/kubedns.yaml.jinja
salt/addons/tiller/init.sls
salt/addons/tiller/tiller.yaml.jinja
salt/cni/init.sls
salt/cni/kube-flannel-rbac.yaml.jinja
salt/dex/dex.yaml
salt/dex/init.sls
salt/dex/roles.yaml

When we create a role, rolebinding etc, we should namespace the names
in order to make it obvious these are deployed as part of CaaSP, as well
as to help ensure these are obviously part of CaaSP, not a stock part of
Kubernetes.
I've gone with a "suse:caasp:" prefix, which matches the "system:" prefix
for built in roles/rolebindings/etc.
Additionally, move a few "kubectl create clusterrolebinding" shell outs over
to the matching YAML files, keeping everything together.

Namespace the roles and cluster roles we create

---

packaging/suse/make_spec.sh

as % is reserved for rpm macros
Signed-off-by: Jordi Massaguer Pla <jmassaguerpla@suse.de>

[packaging] Replace % by # in sed expression

---

salt/haproxy/haproxy.yaml.jinja

Flag the haproxy pods providing connectivity to the API server as critical ones.
This should force kubelet and the scheduler to never ever get rid of them. If these pods are killed to make more space for other ones, the node would not be able to talk with the API server making it useless.
More details inside [upstream doc](https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/).

Mark the haproxy as critical pod

---

config/master.d/50-master.conf

This adds a second pillar root for cloud specific configuration. See also [Add mount for public cloud pillar](https://github.com/kubic-project/caasp-container-manifests/pull/142) in caasp-container-manifests.

Add pillar root for public cloud specific config

---

pillar/params.sls
salt/dex/dex.yaml
salt/kube-apiserver/apiserver.jinja

Previously Velum, CaaSP CLI, and Kubernetes all shared a single Dex
client. From a security perspective, this was far from ideal.
Update Dex with 3 clients, one for each actual client. Both the Velum
and CaaSP CLI clients are allowed to issue tokens for the Kubernetes
client.
Depends-On: https://github.com/kubic-project/velum/pull/439
Depends-On: https://github.com/kubic-project/caasp-cli/pull/9

Use separate Dex clients for each actual client

---

salt/haproxy/haproxy.manifest

Flag the haproxy pods providing connectivity to the API server as critical ones.
This should force kubelet and the scheduler to never ever get rid of
them. If these pods are killed to make more space for other ones, the
node would not be able to talk with the API server making it useless.
More details inside upstream doc:
https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
Signed-off-by: Flavio Castelli <fcastelli@suse.com>
Backport of https://github.com/kubic-project/salt/pull/381

[2.0] Mark the haproxy as critical pod

---

salt/dex/init.sls

In some environments, the external_fqdn is unreachable from inside the
cluster - avoid using it where possible.

Dex: Avoid using the external_fqdn to reach dex

---

salt/dex/dex.yaml

Our dex deployment creates 3 pods running the dex service. There are really high chances (or even certainty in the case of clusters made by 1or 2 worker nodes) that all the dex pods end up running on the same node.
This is bad from a HA perspective, plus we end up taking away resources from small clusters.
With the following change we enforce the kubernetes scheduler to always spread the dex pods over different nodes.
On small clusters (1 or 2 nodes) the deployment will be running with a lower number of replicas until new nodes are added. This doesn't cause our orchestration to fail.
Adding new nodes at a later stage will allow the deployment to reach the desired replica size without any intervention from us or the user.

Dex pods: introduce anti-affinity rule

---

salt/haproxy/haproxy.yaml.jinja
salt/haproxy/init.sls

This avoids a conflict between the caasp-container-manifests package,
and the haproxy package.
Depends-On: https://github.com/kubic-project/caasp-container-manifests/pull/150

Move haproxy config to /etc/caasp/haproxy

---

salt/_modules/caasp_docker.py

Make sure we do not crash on pillars that are not properly formatted by surrounding the code with some `try..except` blocks.

Resist 'None' certs in pillars

---

salt/etcd/update-pre-orchestration.sls
salt/etcd/update-pre-reboot.sls
salt/orch/update.sls

... otherwise we can have some problems is nodes are rebooted in the wrong order.

Assign the etcd role to current members before starting the update orchestration

---

salt/haproxy/haproxy.cfg.jinja
salt/haproxy/init.sls
salt/kube-apiserver/init.sls
salt/orch/kubernetes.sls
salt/orch/update.sls

When executing the highstate make sure the `apiserver` we are checking
is the local one, not *any* master through haproxy.
Fixes: bsc#1079460

When executing a highstate of `apiserver` make sure that we check the local `apiserver` instance

---

salt/haproxy/haproxy.cfg.jinja

Some components have a 60 second timeout for salt request timeouts, e.g the
salt-api server which is called by Velum. Increase this timeout to double
their timeouts to allow the real failures to be disclosed.
We'll likely want to rework how timeouts are handled soon accross all our
components.

Increase haproxy timeouts from 50sec, to 120sec

---

salt/_pillar/velum.py

Add some logging to the Velum pillar module so we can see when
it's get loaded by salt, and when it does not.

Add some additional logging to velum pillar module

---

config/master.d/50-master.conf
salt/haproxy/haproxy.cfg.jinja

It's not possible to reliably bind to 0.0.0.0:443 for one service,
and 127.0.0.1:443 for another service.
As such, we'll move velum-api over to 127.0.0.1:444
Depends-On: https://github.com/kubic-project/caasp-container-manifests/pull/155

Velum Dash and API both attempt to bind to the same port

---

salt/container-feeder/init.sls

container-feeder is a oneshot service, where reload makes no sense
and in unsupported. If this triggers, we ended up getting:
salt-minion[2454]: [ERROR   ] Command '['systemd-run', '--scope', 'systemctl', 'reload', 'container-feeder.service']' failed with return code: 3
salt-minion[2454]: Failed to reload container-feeder.service: Job type reload is not applicable for unit container-feeder.service.

Restart instead of reload container-feeder

---

salt/orch/kubernetes.sls

We should start by refreshing pillar/modules/etc, then once done, move
onto the actual work of deploying CaaSP.

Move disable-rebootmgr state below pillar etc refresh

---

salt/dex/dex.yaml

This can't be met on a cluster of n+2 size (n masters, 2 workers), as we
are creating a deployment of 3.
Let's relax the scheduling from required to preferred.

Relax dex deployment anti-affinity.

---

salt/haproxy/init.sls
salt/ldap/init.sls

This avoids a race condition between docker ps and docker kill/restart.

Don't allow docker restart/kill failures to fail the orch

---

salt/kubelet/update-pre-orchestration.sh

This copies the default labels and annotations from the "old" minion-id based
node to the new hostname based node.
Fixes bsc#1083113

Ensure default labels and annotations are copied when renaming a node

---

salt/kubelet/init.sls

As part of the update process, we are cordoning the nodes, so they don't get new jobs when
we are planning to reboot them. If an update fails for whatever reason, it might happen that
we didn't uncordon the node, but removed the `kubelet:should_uncordon` grain. This would
cause that subsequent retries will never uncordon the worker node again, because without this
grain we'll think that this node was cordoned by the user and will not take any action.

Only remove the `kubelet:should_uncordon` grain when we actually uncordon the node.

---

salt/kubelet/init.sls
salt/orch/update.sls

When we update from 2.0 to 3.0, not only `_modules` have changed, but for example,
`caasp_cmd` has been introduced in `_states`. This can make the orchestration fail:
```
ID: uncordon-node
Function: caasp_cmd.run
Name: kubectl uncordon caasp-worker-0
Result: False
Comment: State 'caasp_cmd.run' was not found in SLS 'kubelet'
Reason: 'caasp_cmd.run' is not available.
Changes:
```
So, make sure that we run `sync_all` on the update process too, and we discover all
the new modules in general, not only `_modules`. After forcefully running `sync_all`
some minions discovered new states.
```
dbf5c05dc8c74fbb8df1fccb105fe3bc:
----------
beacons:
engines:
grains:
log_handlers:
modules:
output:
proxymodules:
renderers:
returners:
sdb:
states:
- states.caasp_cmd
- states.caasp_service
utils:
```

Discover everything (_states, _modules...) when we update, not only modules

---

salt/addons/tiller/tiller.yaml.jinja

This role represents the minimum RBAC requirements needed to make use of
Helm's Tiller service.
Users granted this role on the `kube-system` namespace, or cluster-wide, will be able to use the Tiller service deployed as part of CaaSP.

Add a suse:caasp:tiller-user ClusterRole

---

pillar/cni.sls

Internal constraints won't allow us to use `/opt`, so we'll stick
to `/var/lib/kubelet/cni/bin`.

Remove the TODO message for using the standard `/opt/cni/bin`.

---

salt/orch/update.sls

The admin node might use features not yet discovered, make sure we
run `sync_all` before we enforce a `highstate` on the admin node too.

Run the highstate on the admin after `sync_all` has been called.

---

salt/_pillar/velum.py

There's a race condition in which the cache directory does not exist, but
when tried to be created it has already been created by something else, and
an exception is raised, stopping the execution.
When populating the cache, we don't really care if it was correctly populated
or not in that *specific* call, so move on.
Fixes: bsc#1084441

When populating the cache, don't fail if this fails for some reason.

---

salt/dex/dex.yaml

This will ensure Kubernetes waits for the pods to become ready before
starting to send them traffic, which should in turn prevent the orchestration
proceeding and bootstrap completing until we have at least one working Dex pod
Fixes bsc#1062542

Add liveness/readiness probes to Dex deployment

---

salt/orch/removal.sls

Enforce a new constraint before going ahead with a node removal: we must have at least one k8s minion (otherwise some services like `kube-dns`, `dex`... will have nowhere to run)
https://trello.com/c/O7daOErL

Node removal constraint: we must have at least one k8s minion

---

salt/etc-hosts/init.sls
salt/etc-hosts/update-post-reboot.sls
salt/etc-hosts/update-pre-reboot.sls
salt/orch/update.sls

This ensures the systemd/wicked logic is unaffected by our /etc/hosts
changes.

Wipe out our /etc/hosts changes before reboot

---

salt/addons/dex/manifests/20-deployment.yaml

Delay the liveness probe by 30 seconds, matching the readiness
probe.

Dex: Delay liveness probe in addition to readiness probe

---

salt/orch/removal.sls

This fixes master removal on the salt states. I could remove a master with this patch.
* Salt was complaining that this variable didn't exist in the `orch.removal`
orchestration when removing a master when no replacement was provided.
* If no replacement is provided, `sync-all` was trying to refer to states
that didn't exist because those states also were wrapped with a `replacement`
guard.

Fix undefined variable

---

salt/addons/dex/init.sls
salt/addons/dex/wait.sls
salt/haproxy/haproxy.cfg.jinja
salt/orch/kubernetes.sls
salt/orch/update.sls

When we finish the orchestration all bits and pieces should be working
as expected. Wait for the haproxy on the admin node to be correctly
pointing to dex before finishing the orchestration.

Wait for dex on the admin node before calling the orchestration done

---

pillar/cni.sls
salt/cni/kube-flannel.yaml.jinja

This makes sure flannel has at least reached the point where it starts the
healthz API endpoint. However, that point in the flannel code is *very* early
and not all that useful for actual health checking. Additionally, as long as
the HTTP gorouting is running, healthz will *always* respond with a 200. It
performs no actual health checking.
Even still, lets include the probe. If flannel gets better health checking,
it will be enabled for us, on the other hand, if flannel doesn't get better
health checking, it's still *very slightly* useful to know that flannel has
at least reached this point in it's code.

Add flannel readiness/liveness probe

---

salt/haproxy/init.sls
salt/orch/update.sls

* During a rename, it might happen that `haproxy` refuses to start because it cannot
resolve the new names `nodename.infra.caasp.local` in the configuration because its
`/etc/hosts` file hasn't been updated yet.
* Refresh modules before we call to any `sls`, they might use undiscovered modules.

When we explicitly run `haproxy` sls in the update, run `etc-hosts` too.

---

pillar/certificates.sls

100 days is a very short lifespan, lets bump this to one year - a much more
common value for certificate lifetime.
Related to bsc#1082722

Extend certificates to one year lifespan

---

salt/_macros/kubectl.jinja
salt/addons/dex/deployment-wait.sls
salt/addons/dns/deployment-wait.sls
salt/addons/tiller/deployment-wait.sls
salt/orch/kubernetes.sls
salt/orch/update.sls

Additionally to other checks, we should also consider the orchestration
done once that the expected pods are running.
feature#deployment-stability

Wait for deployments during the orchestration time.

---

salt/kubelet/stop.sls

When trying to drain a node we can get an error if the kubelet is
running a pod created by local manifests (manifests living in the
local filesystem):
```
caasp-admin:~ # kubectl drain --ignore-daemonsets caasp-worker-1
node "caasp-worker-1" cordoned
error: unable to drain node "caasp-worker-1", aborting command...
There are pending nodes to be drained:
caasp-worker-1
error: pods not managed by ReplicationController, ReplicaSet, Job, DaemonSet or StatefulSet (use --force to override): haproxy-caasp-worker-1
```
As opposed to:
```
caasp-admin:~ # kubectl drain --force --ignore-daemonsets caasp-worker-1
node "caasp-worker-1" already cordoned
WARNING: Deleting pods not managed by ReplicationController, ReplicaSet, Job, DaemonSet or StatefulSet: haproxy-caasp-worker-1; Ignoring …
```

Force drain when trying to drain a node

---

salt/orch/removal.sls

Reject keys of removed nodes instead of just deleting them.
https://bugzilla.suse.com/show_bug.cgi?id=1087062
bsc#1087062

Reject keys of removed nodes instead of just deleting them.

---

salt/_modules/caasp_etcd.py
salt/etcd/etcd.conf.jinja
salt/etcd/init.sls
salt/kubelet/stop.sls
salt/orch/removal.sls
salt/orch/update-etc-hosts.sls

Change the meaning of some grains:
* The old `removal_in_progress`/`addition_in_progress` grains have been renamed to `node_removal_in_progress`/`node_addition_in_progress` (set only on the node that is being removed)
* `removal_in_progress` is cluster-wide grain now, used for marking that some node is being removed.
We are currently avoiding the `etc-hosts-update` __only on nodes with `removal_in_progress`__, but now it will be set __in all the nodes__ during the whole orchetsration, so this should avoid conflicts with the etc-hosts-update orchestration...
https://bugzilla.suse.com/show_bug.cgi?id=1087108
bsc#1087108

Fix conflict with the etc-hosts-update orchestration

---

salt/orch/update-etc-hosts.sls
salt/orch/update.sls

Try to resist transient node failures on updates, so users can updte the cluster even if some node X is down.
This can be tested by
1) orchestrating
2) stopping a Salt minion in a node `X` (it can be any master or worker)
3) then trying to run the update orchestration (it can be forced with a _fake_ orchestration, setting the `tx_reboot_needed:true` grain in all those nodes)
The update orchestration sould succeed and all the nodes but `X` should be udpated.
See https://trello.com/c/irviWd1m
feature#update_on_node_failures

Try to resist transient node failures on updates

---

pillar/certificates.sls

100 days is a very short lifespan, lets bump this to one year - a much more
common value for certificate lifetime.
Related to bsc#1082722
Backport of https://github.com/kubic-project/salt/pull/459

[2.0] Extend certificates to one year lifespan

---

.gitignore
salt/_modules/caasp_docker.py
salt/_modules/caasp_etcd.py
salt/_modules/caasp_grains.py
salt/_modules/caasp_log.py
salt/_modules/caasp_net.py
salt/_modules/caasp_nodes.py
salt/_modules/tests/test_caasp_nodes.py
salt/_modules/tests/tests.sh
salt/_states/caasp_etcd.py
salt/orch/kubernetes.sls
salt/orch/removal.sls
salt/orch/update-etc-hosts.sls
salt/top.sls

* Do some code cleanups in `caasp_etcd.py` by using  the same logic for getting etcd replacements as
for getting additional etcd servers when bootstrapping.
* Move most of the removal logic to a `caasp_nodes.py` Python module, as Jinja is not a proper language...
* Add the corresponding unit tests for this new Python code.
* Do not be so strict when finding a replacement: if the replacement is not valid for a k8s master, do not
make it unsuitable for `etcd` too.
* Use a common replacement finder. New replacement finder for k8s masters and minions.
* Try to use some common logging functions
* Refactor out the `grains.get` code to a new `caasp_grains.py` module (as it is shared by several custom modules)
See https://trello.com/c/O7daOErL

Node removal: refactorings and code cleanups

---

pillar/params.sls
salt/addons/dex/manifests/10-clusterrolebinding.yaml
salt/addons/dex/manifests/20-deployment.yaml
salt/addons/dns/init.sls
salt/addons/dns/manifests/10-clusterrolebinding.yaml
salt/addons/psp/init.sls
salt/addons/psp/manifests/10-podsecuritypolicy-privileged.yaml
salt/addons/psp/manifests/10-podsecuritypolicy-unprivileged.yaml
salt/addons/psp/manifests/20-clusterrolebinding.yaml
salt/cni/kube-flannel-rbac.yaml.jinja
salt/cni/kube-flannel.yaml.jinja
salt/kube-apiserver/apiserver.jinja
salt/orch/kubernetes.sls
salt/orch/update.sls

Add support for PodSecurityPolicy's, allowing us to disable use of the
hostPath volume type.
This change adds 2 PSP's:
* unprivileged (Default assigned to all users)
The unprivileged PodSecurityPolicy is intended to be a
reasonable compromise between the reality of Kubernetes workloads, and
suse:caasp:psp:privileged. By default, we'll grant this PSP to all
users and service accounts.
* privileged
The privileged PodSecurityPolicy is intended to be given
only to trusted workloads. It provides for as few restrictions as possible
and should only be assigned to highly trusted users.
Fixes bsc#1047535

Add PodSecurityPolicy Support

---

salt/ldap/init.sls
salt/top.sls
salt/velum/init.sls

Remove unneeded includes `ca-cert` and `cert` for `velum/init.sls` and `ldap/init.sls`

---

pillar/args.sls
salt/kubernetes-common/config.jinja

Right now this PR is made by two commits. The first one is pretty straight forward, the second one is more complicated and needs some discussion.
Kubernetes feature-gates are going to be controlled via a dedicated pillar. We won't expose this pillar inside of Velum because these settings are "dangerous" for the average user; plus they can enable features that we don't support.
The idea is to provide instructions to users who deliberately want to run into this unsupported area of kubernetes. These instructions will involve using some CLI commands.
The first commit allows any kind of feature-gate to be enabled or disabled. This is great because we don't have to provide dedicated boolean pillars for each kind of feature that is supported by kubernetes.
That makes our users independent from …

Feature gates

---

salt/cleanup/remove-post-orchestration.sls
salt/orch/force-removal.sls

Instead of running things on the forced-removal orchestration, move actions to SLS files (so they can be shared with the regular removal orchestration).

Node removal: move forced-removal actions to SLS file

---

salt/cleanup/remove-post-orchestration.sls

This is producing an error on our current salt version:
`Rendering SLS 'base:cleanup.remove-post-orchestration' failed: Jinja error: get()
got an unexpected keyword argument 'tgt_type'`
Go back to using `expr_form` until we update.
feature#deployment-stability

Use `expr_form` instead of `tgt_type` until we update salt

---

salt/kubelet/init.sls

We have to ensure the swap state is executed before the kubelet service is started, otherwise kubelt won't run and this will lead to issues like the ones causing bsc#1090337

Ensure swap is disabled before kubelet is started

---

salt/container-feeder/init.sls

This service does not support reloading, so it doesn't make sense to
ask for a reload of this service. It makes the bootstrap orchestration
fail.
It's a one-shot service, so in any case I doubt we need this in our
salt states at all (always after a new snapshot is booted,
`container-feeder` will load all images first thing) -- the only reason
we should keep this is because it ensures the service is enabled for
a reboot, but when this is ran it's when we are already in the new
snapshot.
Fixes: bsc#1070989

[2.0] Do not instruct salt to reload the `container-feeder` service

---

salt/container-feeder/init.sls

This service does not support reloading, so it doesn't make sense to
ask for a reload of this service. It makes the bootstrap orchestration
fail.
It's a one-shot service, so in any case I doubt we need this in our
salt states at all (always after a new snapshot is booted,
`container-feeder` will load all images first thing) -- the only reason
we should keep this is because it ensures the service is enabled for
a reboot, but when this is ran it's when we are already in the new
snapshot.
Fixes: bsc#1070989

[2.1] Do not instruct salt to reload the `container-feeder` service

---

salt/orch/update.sls

Without doing this, fixes like `fe3e5c8eccd9b48c` render completely
invalid as we won't regenerate the LDAP certificate when the upgrade
happens.
While `fe3e5c8eccd9b48c` fixed the issue for new bootstraps on 2.0
(because the `orch.kubernetes` orchestration highstates the admin),
this would never work with maintenance requests of an already
bootstrapped cluster.
Fixes: bsc#1069175

[2.0] When we are upgrading between releases (2.0 -> updates), we need to also highstate the admin node as we do on 3.0

---

salt/_modules/caasp_etcd.py

caasp_etcd.get_member_id was referencing a variable that doesn't exist.

Fix caasp_etcd.get_member_id error handling

---

salt/_modules/caasp_nodes.py
salt/cleanup/remove-post-orchestration.sls
salt/kube-apiserver/init.sls
salt/orch/removal.sls

* Fix the `remove-cluster-wide-removal-grain` stage: I forgot the `tgt_type: compound`.
* In some cases (when applying post-bootstrap highstates?), the kubernetes API server can return a `599 Timeout` and our `wait_for_successful_query` seems to fail fast. Retry several times just in case.
* Use the same `cleanup.post-orchestration` that the `forced-removal` uses.
* Some other removal orchestration fixes and improvements.

Node removal: fix error when removing grain

---

pillar/cri.sls
salt/_modules/caasp_cri.py

* Allow more time for the CRI socket to become active - 60 seconds
* Explicitly fail if the socket does not become active within this
time.
Related to bsc#1091419

Harden the waiting for CRI socket to become active

---

config/master.d/50-master.conf
config/master.d/50-returner.conf

Configure salt-master to read public cloud pillar
Configure mysql pillar to support public cloud specific datanae pillars
that have more nested levels and also require a list data set.
Depends-On: https://github.com/kubic-project/caasp-container-manifests/pull/172

[2.1] salt-master config: support public cloud

---

salt/_modules/caasp_net.py

For some unknown reason `get_primary_ip` is sometimes failing when it tries to find data in the mine for a host. So do not try to use the mine when we can get the same information with a module.
(cherry picked from commit dfd3b8a6a65c7d969466b09a1f20536a525ae42a)
bsc#1091077

Fix get_primary_ip()

---

pillar/params.sls
salt/_modules/caasp_net.py
salt/etc-hosts/hosts.jinja

For some unknown reason, the mine can contain data about a node `X` after removing `X` from the cluster. However, when minions try to get some data about `X` (like the IP address), that information is not there and we get an exception. This problem seems to appear only when generating the `/etc/hosts` file.
This PR tries to resist that data missing by just returning empty values and skipping these hosts in `/etc/hosts`. Some hosts will have an entry for node `X` in  their `/etc/hosts` while some others will not...
https://bugzilla.suse.com/show_bug.cgi?id=1091361
bsc#1091361

Try to resist inexistent data in the mine

---

pillar/params.sls
salt/_modules/caasp_pillar.py
salt/kubelet/kubelet.jinja

Allow kubelet to take into account resource reservation and eviction
threshold.
It's possible to reserve resources for the `kube` and the `system`
components.
The `kube` component is the one including the kubernetes components:
api server, controller manager, scheduler, proxy, kubelet and the container
engine components (docker, containerd, cri-o, runc).
The `system` component is the `system.slice`, basically all the system
services: sshd, cron, logrotate,...
By default don't specify any kind of resource reservation. Note well:
when the resource reservations are in place kubelet will reduce the
amount or resources allocatable by the node. However **no** enforcement
will be done neither on the `kube.slice` nor on the `system.slice`.
This is not happening because:
* Resource enforcement is …

kubelet: allow resource reservation

---

salt/_modules/caasp_cri.py
salt/_modules/caasp_nodes.py
salt/container-feeder/init.sls
salt/haproxy/init.sls
salt/top.sls

Some of our states are now depending on `crictl` tool. All these states have to depend on the `kubelet service.running` one, otherwise the `crictl` socket won't be available and the state will fail.
Also, with these changes, the "blame" of a failure should point directly to the guilty (`kubelet` service not running for whatever reason) instead of falling on the `haproxy` one.
Finally, the check looking for `crictl` socket has been changed to ensure the socket file exists and the service is actually listening.
This will help with bugs like bsc#1091419

Make crictl handling more robust

---

salt/crio/remove-pre-reboot.sls
salt/crio/stop.sls

This is required to fix node removal on clusters using CRI-O as CRI.
Fixes bsc#1092614

Add missing cri-o removal states

---

pillar/certificates.sls
salt/_macros/kubectl.jinja
salt/addons/dex/init.sls
salt/addons/dex/manifests/20-deployment.yaml
salt/addons/dns/init.sls
salt/addons/tiller/init.sls
salt/addons/tiller/manifests/20-deployment.yaml
salt/cni/init.sls
salt/cni/kube-flannel.yaml.jinja
salt/cni/update-pre-orchestration.sh
salt/haproxy/haproxy.cfg.jinja
salt/haproxy/haproxy.yaml.jinja
salt/haproxy/init.sls
salt/kube-apiserver/apiserver.jinja
salt/kube-apiserver/init.sls
salt/kubelet/init.sls
salt/kubelet/stop.sls
salt/kubelet/update-post-start-services.sls
salt/kubelet/update-pre-orchestration.sh

This allows us to add fine-grained timeouts depending on the endpoint being
accessed or with what parameters (e.g. /log?follow=true should have no
timeout as happens on the apiserver). /exec is another example, but in this
case the protocol is upgraded to spdy.
Depends on https://github.com/kubic-project/caasp-container-manifests/pull/164
Depends on https://github.com/kubic-project/automation/pull/377
Fixes: bsc#1071994

Make HAProxy work as an http proxy instead of a tcp proxy.

---

pillar/certificates.sls
salt/_macros/kubectl.jinja
salt/addons/dex/init.sls
salt/addons/dex/manifests/20-deployment.yaml
salt/addons/dns/init.sls
salt/addons/tiller/init.sls
salt/addons/tiller/manifests/20-deployment.yaml
salt/cni/init.sls
salt/cni/kube-flannel.yaml.jinja
salt/cni/update-pre-orchestration.sh
salt/haproxy/haproxy.cfg.jinja
salt/haproxy/haproxy.yaml.jinja
salt/haproxy/init.sls
salt/kube-apiserver/apiserver.jinja
salt/kube-apiserver/init.sls
salt/kubelet/init.sls
salt/kubelet/stop.sls
salt/kubelet/update-post-start-services.sls
salt/kubelet/update-pre-orchestration.sh

This allows us to add fine-grained timeouts depending on the endpoint being
accessed or with what parameters (e.g. /log?follow=true should have no
timeout as happens on the apiserver). /exec is another example, but in this
case the protocol is upgraded to spdy.
Fixes: bsc#1071994
(cherry picked from commit 442a76cad214f2308f6a1de0ddef8febca8074c8)

[3.0] Make HAProxy work as an http proxy instead of a tcp proxy.

---

salt/orch/update-etc-hosts.sls

It seems that the `update-etc-hosts` orchestration can conflict with... itself. Apparently this can happen when a new orchestration has been started and the previous one has not finished yet. This tried to solve that problem by queueing the only problematic part of the orchestration, the `salt.state` clause.
Fixes part of bsc#1093123

Queue the /etc/hosts update when triggered from a reactor.

---

salt/_modules/caasp_http.py
salt/_states/caasp_http.py
salt/addons/dex/wait.sls
salt/haproxy/init.sls
salt/kube-apiserver/init.sls

When we are waiting for some service to be up, if the request hangs for
some reason, we want to retry at least several times. Without setting
this value explicitly, it takes the default (`http_request_timeout` as 3600),
what is way over our `wait_for` argument set at 300 seconds.
By setting the default `http_request_timeout` to a more reasonable default
when doing this kind of checks we can ensure that the request itself will
timeout several times before we call it done.
Fixes: bsc#1093540
Fixes: bsc#1093685

Lower the per-request timeout when we are checking for successful query

---

salt/_modules/caasp_http.py
salt/_states/caasp_http.py
salt/addons/dex/wait.sls
salt/haproxy/init.sls
salt/kube-apiserver/init.sls

When we are waiting for some service to be up, if the request hangs for
some reason, we want to retry at least several times. Without setting
this value explicitly, it takes the default (`http_request_timeout` as 3600),
what is way over our `wait_for` argument set at 300 seconds.
By setting the default `http_request_timeout` to a more reasonable default
when doing this kind of checks we can ensure that the request itself will
timeout several times before we call it done.
Fixes: bsc#1093540
Fixes: bsc#1093685
(cherry picked from commit 876f7c7f03c3c6c970ba6f81fa4c676d5ea43b03)

[3.0] Lower the per-request timeout when we are checking for successful query

---

salt/kubelet/stop.sls

By default, the grace period is -1, or whatever the pod specifies on
its `terminationGracePeriodSeconds` spec. The pod can know better than
us what it needs to cleanly stop, and we don't need to apply arbitrary
timeouts. If this is not specified, the default `terminationGracePeriodSeconds`
value is 30 seconds. After this grace termination period, a SIGKILL will
be sent to the process when evicting pods.
Aside from this, we should have an "inifinite" timeout. Given that this
process doesn't stall, it's safer to perform this operation until it
succeeds. If we have proof that this is causing problems we should add
a timeout, but in general the draining process should not hang.
The alternative is in reality the real problem: if we timeout the draining
process, it can happen that certain pods …

[3.0] Remove default grace period and timeout when draining a node.

---

salt/kubelet/stop.sls

By default, the grace period is -1, or whatever the pod specifies on
its `terminationGracePeriodSeconds` spec. The pod can know better than
us what it needs to cleanly stop, and we don't need to apply arbitrary
timeouts. If this is not specified, the default `terminationGracePeriodSeconds`
value is 30 seconds. After this grace termination period, a SIGKILL will
be sent to the process when evicting pods.
Aside from this, we should have an "inifinite" timeout. Given that this
process doesn't stall, it's safer to perform this operation until it
succeeds. If we have proof that this is causing problems we should add
a timeout, but in general the draining process should not hang.
The alternative is in reality the real problem: if we timeout the draining
process, it can happen that certain pods …

Remove default grace period and timeout when draining a node.

---

salt/addons/dex/init.sls
salt/docker/init.sls
salt/etcd/init.sls
salt/kube-apiserver/init.sls
salt/kube-controller-manager/init.sls
salt/kube-proxy/init.sls
salt/kube-scheduler/init.sls
salt/kubelet/init.sls
salt/kubernetes-common/init.sls
salt/repositories/containers.repo
salt/repositories/init.sls
salt/top.sls

The registries state is something from the early days of caasp.
Something we don't need (and use) anymore.
feature#remove-unneeded-code-registries
Signed-off-by: Flavio Castelli <fcastelli@suse.com>

Remove unneeded state

---

pillar/kube-master.sls
salt/kube-apiserver/apiserver.jinja
salt/kube-apiserver/init.sls

Allow users to enable kubernetes API server auditing feature.
The auditing will produce an audit log file locally that can then be pushed to a central logging solution (eg: by using a fluentd daemonset running on the master nodes).
By default there's no auditing in place. This is enabled only when the user provides a value for each one of the new pillars introduced by this commit.
feature#kube-api-audit
fate#325337
For more information: https://v1-9.docs.kubernetes.io/docs/tasks/debug-application-cluster/audit/#log-backend

Add support for kube API auditing

---

.gitignore
Jenkinsfile.tests
salt/_modules/tests/test_caasp_etcd.py
salt/_modules/tests/tests.sh
tox.ini

Example to run them locally:
tox -e tests-salt-2016.11.4-py27
or:
tox -e tests-salt-2016.11.4-py34

[WIP] Allow salt tests to be ran via tox and Jenkins

---

salt/kube-apiserver/apiserver.jinja

(cherry picked from commit 6c4ec0c05fdfd9991869bb21f51c2d0ec3afab18)
backport of #536

[3.0] skip removed etcd servers (bsc#1093305)

---

salt/_modules/caasp_cri.py

Related: bsc#1093918
(cherry picked from commit c5fb8d2158bc17553141c81028455963e4cf1791)
Backport of https://github.com/kubic-project/salt/pull/560

[3.0] Log all CRI issues as we go, and show them if we really timeout

---

salt/_modules/caasp_docker.py
salt/_states/caasp_cmd.py
salt/_states/caasp_retriable.py
salt/_states/caasp_service.py

Fix imports that do no longer exist in `python3` and no longer use the `xrange` function.

Use six compatibility library

---

salt/kubelet/kubelet.jinja

Remove unsupported `--require-kubeconfig` argument deprecated in Kubernetes (and removed in 1.10)

Fix kubelet arguments

---

salt/kubelet/kubelet.jinja

Remove unsupported `--require-kubeconfig` argument deprecated in Kubernetes (and removed in 1.10)
Backport of https://github.com/kubic-project/salt/pull/562

[3.0] Fix kubelet arguments

---

salt/_modules/caasp_etcd.py
salt/_modules/caasp_grains.py
salt/_modules/caasp_net.py
salt/_modules/caasp_nodes.py
salt/_modules/tests/test_caasp_nodes.py
salt/_states/caasp_cri.py
salt/_states/caasp_http.py
salt/_states/caasp_retriable.py
salt/_states/caasp_service.py
salt/etc-hosts/hosts.jinja
salt/etcd/etcd.conf.jinja
salt/haproxy/haproxy.cfg.jinja
salt/orch/removal.sls

* Fix targets when calculating a replacement. For example, when getting a replacement for a `kube-master`, we were looking for `G@roles:etcd`, when we should look for `G@roles:etcd and not G@roles:kube-master`.
* Do not include removed nodes when generating `haproxy.cfg`
* Refactorings in the `get_with_expr()` code
* Do not use unassigned nodes when looking for a replacement.
* Minor cleanups
See https://trello.com/c/eKXnJbzz and https://trello.com/c/mKb0nykK

Fix targets when calculating a replacement.

---

salt/_modules/caasp_etcd.py
salt/_modules/caasp_grains.py
salt/_modules/caasp_net.py
salt/_modules/caasp_nodes.py
salt/_modules/tests/test_caasp_nodes.py
salt/_states/caasp_cri.py
salt/_states/caasp_http.py
salt/_states/caasp_retriable.py
salt/_states/caasp_service.py
salt/etc-hosts/hosts.jinja
salt/etcd/etcd.conf.jinja
salt/haproxy/haproxy.cfg.jinja
salt/orch/removal.sls

Backport of #581.
* Fix targets when calculating a replacement. For example, when getting a replacement for a `kube-master`, we were looking for `G@roles:etcd`, when we should look for `G@roles:etcd and not G@roles:kube-master`.
* Do not include removed nodes when generating `haproxy.cfg`
* Refactorings in the `get_with_expr()` code
* Do not use unassigned nodes when looking for a replacement.
* Minor cleanups
See https://trello.com/c/eKXnJbzz and https://trello.com/c/mKb0nykK

[3.0] fix get node targets

---

salt/etcd/remove-pre-orchestration.sls
salt/kube-apiserver/remove-pre-orchestration.sls
salt/orch/removal.sls

When doing node removals, we have run into problems in the past because the cluster was not really healthy before starting the removal (so the removal made things even worse). And the node removal orchestration cannot be a 'fix-my-cluster" orchestration either...
So instead of messing things up even more, do some simple stability checks before trying to start the removal. If these checks fail, we will abort the orchestration.

Perform some checks before starting the node removal.

---

salt/kubelet/init.sls
salt/kubelet/update-post-start-services.sls
salt/orch/update.sls

This way we don't try to uncordon the node in the `kubelet/init.sls` file,
required for example by `haproxy`, that will end up in the machine trying
to early uncordon itself (when `haproxy` configuration hasn't been written
yet, and leading to early failure).
Splitting this action and called only when required (this is: the update
process) is safer.
Fixes: bsc#1080978
(cherry picked from commit 02f063385e3a8cd435a76280ca246a87099a01d5)
Backport of https://github.com/kubic-project/salt/pull/584

[3.0] Uncordon node in a explicit sls action

---

salt/kubelet/init.sls
salt/kubelet/update-post-start-services.sls
salt/orch/update.sls

This way we don't try to uncordon the node in the `kubelet/init.sls` file,
required for example by `haproxy`, that will end up in the machine trying
to early uncordon itself (when `haproxy` configuration hasn't been written
yet, and leading to early failure).
Splitting this action and called only when required (this is: the update
process) is safer.
Fixes: bsc#1080978

Uncordon node in a explicit sls action

---

salt/orch/update.sls

If some important change lands between Kubernetes updates, it might
happen that since we don't disable the `kubelet` service on the master
nodes, when the machine gets rebooted, `systemd` will try to start the
`kubelet` service, failing in a burst mode.
This will prevent our salt states from trying to start it again, because
the service will be in a failed state. Stop the service and disable it
on the masters too when we are performing an upgrade, this way we are sure
that we'll try to start and enable it when we have performed the required
changes for it to succeed.
Fixes: bsc#1096768

Also stop `kubelet` on masters when performing an upgrade

---

salt/orch/update.sls

If some important change lands between Kubernetes updates, it might
happen that since we don't disable the `kubelet` service on the master
nodes, when the machine gets rebooted, `systemd` will try to start the
`kubelet` service, failing in a burst mode.
This will prevent our salt states from trying to start it again, because
the service will be in a failed state. Stop the service and disable it
on the masters too when we are performing an upgrade, this way we are sure
that we'll try to start and enable it when we have performed the required
changes for it to succeed.
Fixes: bsc#1096768
(cherry picked from commit ec6238cb4d43983cce7c708b677c9e99e508d787)

[3.0] Also stop `kubelet` on masters when performing an upgrade

---

salt/orch/update.sls

Before the real update orchestration happens we are updating etcd
certificates, so this machine isn't left isolated. However, in this
process, the configuration for etcd might refer to the new machine
names if this happens during the upgrade of 2.0 to 3.0. This might
leave the etcd instances in a state in which they cannot resolve
other etcd peer names (because their `/etc/hosts` file is outdated).
In order to prevent this, force the `etc-hosts` sls to be run before
we execute the `etcd` sls, so we are sure that `/etc/hosts` will
contain both the old and the new names during the upgrade, and etcd
will be able to refer to other peers using the new hostnames.
Fixes: bsc#1096750

Force `etc-hosts` sls to be run before `etcd`

---

salt/orch/update.sls

Before the real update orchestration happens we are updating etcd
certificates, so this machine isn't left isolated. However, in this
process, the configuration for etcd might refer to the new machine
names if this happens during the upgrade of 2.0 to 3.0. This might
leave the etcd instances in a state in which they cannot resolve
other etcd peer names (because their `/etc/hosts` file is outdated).
In order to prevent this, force the `etc-hosts` sls to be run before
we execute the `etcd` sls, so we are sure that `/etc/hosts` will
contain both the old and the new names during the upgrade, and etcd
will be able to refer to other peers using the new hostnames.
Fixes: bsc#1096750
(cherry picked from commit 23ce1f28cc1c35b12ac43c57ec265dcb19a53611)

[3.0] Force `etc-hosts` sls to be run before `etcd`

---

salt/orch/force-removal.sls
salt/orch/removal.sls

This will avoid to render stale information about critical components,
like `etcd` endpoints in the `etcd` configuration.
`etcd` is very sensitive to this kind of misleading (stale) information,
if more endpoints are provided in `ETCD_INITIAL_CLUSTER` than the ones
that actually exist in the cluster, a new instance of etcd will refuse
to start.
Fixes: bsc#1097001
Fixes: bsc#1097147
(cherry picked from commit cf5b83bb8bbb867178945cf60155378dee657bae)

[3.0] Remove mine information when removing a node

---

salt/orch/force-removal.sls
salt/orch/removal.sls

This will avoid to render stale information about critical components,
like `etcd` endpoints in the `etcd` configuration.
`etcd` is very sensitive to this kind of misleading (stale) information,
if more endpoints are provided in `ETCD_INITIAL_CLUSTER` than the ones
that actually exist in the cluster, a new instance of etcd will refuse
to start.
Fixes: bsc#1097001
Fixes: bsc#1097147

Remove mine information when removing a node

---

salt/addons/psp/manifests/10-podsecuritypolicy-privileged.yaml
salt/addons/psp/manifests/10-podsecuritypolicy-unprivileged.yaml
salt/orch/update.sls

Backport of #597 
We are currently upgrading the cluster in this way:
1) for each machine
1.1) stop flannel and so 
1.2) reboot into a new version with no flannel daemon, only a CNI&flannel image
2) after all nodes have been upgraded, load CNI
So we are loosing connectivity one by one until we restore it when we load the CNI manifest.
In conclusion, we cannot wait until all the machines are updated for loading these manifests (CNI and the PSP). But it is not a good idea to load them before doing the update because these manifests could be incompatible with the old cluster.
So the "best" solution is to load them before we start the masters update. This could be problematic in some cases (as the new  manifests will be verified by an old cluster), buut there is no other alternative... …

[3.0] Early setup some services on updates

---

salt/addons/init.sls
salt/addons/psp/init.sls
salt/cni/init.sls
salt/cni/update-post-reboot.sls
salt/orch/update.sls

Move the early services setup even before updating the masters (we can do this by removing some
unnecessary dependencies).
bsc#1096992

[3.0] Move the early services setup before updating the masters

---

salt/kubelet/kubelet.jinja

kubernetes 1.10 uses /usr/libexec by default which doesnt exist,
and we want to stick with /usr/lib
kubelet config fix in the package is part of https://build.opensuse.org/request/show/612897

override volume plugin dir (bsc#1084766)

---

config/master.d/50-returner.conf

this affects only kubic for now where we use PyMySQL
we cant use the MYSQL_UNIX_PORT workaround anymore as we could
do with MySQLdb
salt#mysql-unix-socket

explicitly pass unix_socket

---

salt/kubelet/update-pre-orchestration.sh
salt/kubelet/update-pre-orchestration.sls

When migrating from the "old" to "new" names for the kubelets, we pre-create
the new node so that we can clone the network config. This means the kubelet
is NOT self-registering, and the "single use options" like --register-with-taints
are ignored. This means the kubelet is connected from the period of time where it
starts, to where salt later forcefully adds the taint. Any pods created during
this window could end up scheduled to the master.
bsc#1098383

During upgrade, ensure masters always have the correct taints

---

salt/orch/update.sls

During an upgrade we want to call to `mine.update` after `saltutil.sync_pillar`
has been called, because the `mine_functions` reside on the pillar, we first want
to make sure to sync that, and update the mine afterwards. Otherwise, we risk
doing this in a race condition when the salt minion starts, and it could or
could not lead to update orchestration failure.
Fixes: bsc#1097478
(cherry picked from commit 97d81781d8bb7ad7586caa5c613f6b5003106873)

[3.0] Call to `mine.update` after `saltutil.sync_pillar` has been called.

---

salt/orch/update.sls

During an upgrade we want to call to `mine.update` after `saltutil.sync_pillar`
has been called, because the `mine_functions` reside on the pillar, we first want
to make sure to sync that, and update the mine afterwards. Otherwise, we risk
doing this in a race condition when the salt minion starts, and it could or
could not lead to update orchestration failure.
Fixes: bsc#1097478

Call to `mine.update` after `saltutil.sync_pillar` has been called.

---

pillar/params.sls
salt/kubernetes-common/openstack-config.jinja

Ignore OpenStack Cinder avability zone when attaching volumes.
When Nova and Cinder have different availability zones,
this should be set to true. Default is false.

[CPI] Option to ignore OpenStack Cinder availability zone, bsc#1095572

---

salt/orch/update.sls

Fixes: bsc#1101124
(cherry picked from commit f0a0ac1bd1190ee1989eaa9d06fc9da272b3e2ea)
Backport of https://github.com/kubic-project/salt/pull/628

[3.0] Batch potentially dangerous and massive operations.

---

salt/addons/dns/manifests/20-deployment.yaml
salt/addons/tiller/manifests/20-deployment.yaml

Sometimes, Kubernetes will schedule all replicas of an addon to the same
machine. Defeating much of the purpose of running multiple replicas.
Configure all addons with affinity rules to encourage Kubernetes to spread
these pods around the available machines.
bsc#1101805

Configure addon pod affinity

---

config/master.d/50-reactor.conf
config/master.d/50-returner.conf
reactor/sync-modules.sls
reactor/update-mine.sls
salt/_beacons/default_network_interface_settings.py
salt/_modules/caasp_filters.py
salt/_modules/caasp_http.py
salt/_modules/caasp_log.py
salt/_modules/caasp_nodes.py
salt/addons/dex/init.sls
salt/orch/update.sls

Backport of #607.
(Right now there is no `fix bnc#<NR>` as there is not real a bnc that is `fixed` by this backport)

[3.0] Salt 2018 compatibility

---

config/master.d/50-reactor.conf
reactor/sync-modules.sls
reactor/update-mine.sls
salt/_beacons/default_network_interface_settings.py
salt/_modules/caasp_filters.py
salt/_modules/caasp_http.py
salt/_modules/caasp_log.py
salt/_modules/caasp_nodes.py
salt/addons/dex/init.sls
salt/orch/update.sls

Changes required to make our salt states run with `salt 2018.3`.

Salt 2018 compatibility

---

salt/haproxy/init.sls

In a context in which cloud-init could be updating the hostnames after
machines are continuing with the update orchestration, we could be
writing one thing to `/etc/hosts` and another one in the `haproxy`
configuration, refusing this one to start because it cannot resolve
the new name.
This easily fixable in a newer HAProxy version by using the `init-addr`
configuration, so HAProxy won't refuse to start if it cannot resolve
any backend -- it will just ignore it --.
For now, let's make the temporal window as small as possible, making
the `haproxy` init.sls depend on the `etc-hosts` SLS, as it's *so*
dependant on it.
However, this is not in any way an ideal fix; rather a way to make
this problematic window as small as possible.
Fixes: bsc#1097478
Please, refer to …

HAProxy will refuse to start if it cannot resolve any name.

---

salt/_modules/caasp_etcd.py
salt/_states/caasp_etcd.py

This would not work as what is fork + exec'ed is the `ETCDCTL_API=version`,
what is not found in the `PATH`, causing the whole command to fail.
Besides, each version produces a different output, and the parsing needs to
be updated in order to properly get the member id.
Follow up of https://github.com/kubic-project/salt/pull/622

Pass `ETCDCTL_API` version as an envvar instead of at the command name.

---

pillar/params.sls
salt/kubelet/stop.sls

This is a partial revert of 03d371fc489f4bd0e15da348b60390aa558daf76. We reintroduce
the --timeout flag, leaving --grace-period unset (thus, inheriting from from the Pods
terminationGracePeriodSeconds value). Without this, kubectl drain can hang forever in
certain circumstances.
Additionally, should the drain fail, then fail the orchestration. This ensures that we
do not reboot a node which has, for example, SES/Ceph mounts active, which would in
turn cause systemd to hang as the machine is rebooted.
bsc#1104217

Reintroduce kubelet drain timeout and abort if draining fails

---

salt/transactional-update/10-increase-update-speed.conf.jinja
salt/transactional-update/10-update-rebootmgr-options.conf
salt/transactional-update/init.sls

Admins want to override themselves how often the system updates, so removed the configuration files we where setting up.
Fix bsc#1101004
Signed-off-by: Vicente Zepeda Mas <vzepedamas@suse.com>

Fix bsc#1101004 removes extra configuration for transactional updates

---

pillar/params.sls

Transactional Update pillars where left behind after the removal of the configuration files.
There are not being used anymore hence the need to remove them.

Fix bsc#1101004 removes unsused pillars for transactional updates

---

salt/addons/dex/manifests/10-rolebinding.yaml

This RoleBinding allows unauthenticated users (such as those using caasp-cli)
to find the Dex service endpoint.
This was dropped in 3cdcfaedb2d029694a34fbcb147087eccea3e25a
bsc#1104658

Create RoleBinding to allow dex discovery

---

salt/haproxy/init.sls

In a context in which cloud-init could be updating the hostnames after
machines are continuing with the update orchestration, we could be
writing one thing to `/etc/hosts` and another one in the `haproxy`
configuration, refusing this one to start because it cannot resolve
the new name.
This easily fixable in a newer HAProxy version by using the `init-addr`
configuration, so HAProxy won't refuse to start if it cannot resolve
any backend -- it will just ignore it --.
For now, let's make the temporal window as small as possible, making
the `haproxy` init.sls depend on the `etc-hosts` SLS, as it's *so*
dependant on it.
However, this is not in any way an ideal fix; rather a way to make
this problematic window as small as possible.
Fixes: bsc#1097478
(cherry picked from commit …

[3.0] HAProxy will refuse to start if it cannot resolve any name.

---

salt/addons/dex/manifests/10-rolebinding.yaml

This RoleBinding allows unauthenticated users (such as those using caasp-cli)
to find the Dex service endpoint.
This was dropped in 3cdcfaedb2d029694a34fbcb147087eccea3e25a
bsc#1104658
(cherry picked from commit 904eac64aab5b39529e51aaee95e80b3bc943ec9)
Backport of https://github.com/kubic-project/salt/pull/648

[3.0] Create RoleBinding to allow dex discovery

---

pillar/params.sls
salt/kubelet/stop.sls

This is a partial revert of 03d371fc489f4bd0e15da348b60390aa558daf76. We reintroduce
the --timeout flag, leaving --grace-period unset (thus, inheriting from from the Pods
terminationGracePeriodSeconds value). Without this, kubectl drain can hang forever in
certain circumstances.
Additionally, should the drain fail, then fail the orchestration. This ensures that we
do not reboot a node which has, for example, SES/Ceph mounts active, which would in
turn cause systemd to hang as the machine is rebooted.
bsc#1104217
(cherry picked from commit 17bf89a3a784ad597db1e03bd407e5c8dbe3ab0d)
Backport of https://github.com/kubic-project/salt/pull/646

[3.0] Reintroduce kubelet drain timeout and abort if draining fails

---

salt/addons/dex/manifests/15-configmap.yaml

This is a backport of a single commit:  _**[Add configmap from pillar data to dex ldap connectors](https://github.com/kubic-project/salt/pull/606)**_ (cherry-picked from [a609b3c](https://github.com/kubic-project/salt/pull/606/commits/a609b3c8ed0c62d0f35678678701bb061fd238cd)).  This is the companion to the **_[Velum Backport of LDAP external auth feature](https://github.com/kubic-project/velum/pull/657)_** pull request.

Salt Backport of LDAP external auth feature

---

salt/orch/update.sls

If the masters already updated, but workers failed to update this state will
not have any minions to run on and fail if 'execpt_minions: false' is not set.
(cherry picked from commit 9786217d2e68d9d130522eb3aa8a43d4007f685e)

[3.0] Fix bsc#1111168: Do not expect masters to always need to be updated

---

salt/addons/dns/manifests/20-deployment.yaml
salt/addons/tiller/manifests/20-deployment.yaml

Sometimes, Kubernetes will schedule all replicas of an addon to the same
machine. Defeating much of the purpose of running multiple replicas.
Configure all addons with affinity rules to encourage Kubernetes to spread
these pods around the available machines.
bsc#1101805
Backport of https://github.com/kubic-project/salt/pull/632

[3.0] Configure addon pod affinity

---

salt/kubelet/kubelet.jinja

This PR disables CAdvisor in kubelet.
(Cherry picked from commit 985323ba9f9912c1493053f9f95a630ab48112ef)

[3.0] CAdvisor is publicly exposed on the kubernetes nodes(:::4194) (bsc#1105910)

---

pillar/params.sls
salt/_modules/caasp_etcd.py
salt/_modules/caasp_nodes.py
salt/_modules/tests/test_caasp_etcd.py
salt/_states/caasp_etcd.py
salt/cleanup/etcd.sls
salt/etcd/etcd.conf.jinja
salt/etcd/etcdctl.conf.jinja
salt/etcd/init.sls
salt/etcd/remove-pre-orchestration.sls
salt/etcd/remove.sls
salt/kube-apiserver/remove-pre-orchestration.sls
salt/kubelet/remove-post-orchestration.sls
salt/orch/force-removal.sls
salt/orch/kubernetes.sls
salt/orch/removal.sls

Improve `etcd` configuration handling to allow it to grow as needed. This
change includes:
* Adding several masters at the same time
* `etcd` will grow instance by instance still, as recommended by the `etcd` administration best practices.
* Try to use the current endpoints reported by `etcd`. This makes much
easier to grow several instances one by one without having to relay
on internal hacks to properly set up `ETCD_INITIAL_CLUSTER` environment
variable.
* Add helper methods that allow us to list current members (active and
unstarted)
* Differentiate between the first bootstrap (`ETCD_INITIAL_CLUSTER_STATE`
defaults to `new`) and *any* other run, where `ETCD_INITIAL_CLUSTER_STATE`
will be `existing`, as the `etcd` cluster is already running.
When we grow, we take into account the golden …

[3.0] Allow `etcd` to grow as required and shrink to optimal etcd cluster sizes on corner cases

---

salt/crypto/init.sls

we tried to run zypper from within the ca container which tried
to fetch from the sles repos

[3.0] fix for bsc#1111333

---

salt/_modules/caasp_etcd.py
salt/_modules/caasp_nodes.py
salt/_modules/tests/test_caasp_etcd.py
salt/_states/caasp_etcd.py
salt/cleanup/etcd.sls
salt/etcd/etcd.conf.jinja
salt/etcd/init.sls
salt/etcd/remove.sls
salt/kubelet/remove-post-orchestration.sls
salt/orch/force-removal.sls
salt/orch/kubernetes.sls
salt/orch/removal.sls

Improve `etcd` configuration handling to allow it to grow as needed. This
change includes:
* Adding several masters at the same time
* `etcd` will grow instance by instance still, as recommended by the `etcd` administration best practices.
* Try to use the current endpoints reported by `etcd`. This makes much
easier to grow several instances one by one without having to relay
on internal hacks to properly set up `ETCD_INITIAL_CLUSTER` environment
variable.
* Add helper methods that allow us to list current members (active and
unstarted)
* Differentiate between the first bootstrap (`ETCD_INITIAL_CLUSTER_STATE`
defaults to `new`) and *any* other run, where `ETCD_INITIAL_CLUSTER_STATE`
will be `existing`, as the `etcd` cluster is already running.
When we grow, we take into account the golden …

Allow `etcd` to grow as required and shrink to optimal etcd cluster sizes on corner cases

---

salt/addons/dex/manifests/15-configmap.yaml

This complements the Velum PR at kubic-project/velum#665 by adding OIDC connector listing support to salt.
NOTE: Do not merge until kubic-project/velum#665 is merged, though, as it will cause orchestration to fail if the new database table (created in that PR) does not exist.  Marking as Work In Progress, since cross-project PR dependencies isn't a thing in GitHub yet. :)

Add support for OIDC connectors to dex configmap

---

config/master.d/50-master.conf

Fixes: bsc#1112967
Backport of https://github.com/kubic-project/salt/pull/678/

[3.0] Add a whitelist for returned events so we only save events that we care about

---

salt/orch/update.sls

in case of a kubernetes update from 1.9 to 1.10 we can't afford
to stop kubernetes through the haproxy states, because it will
not be able to restart as the --config file flag has changed
between those releases
the update orchestration fails in the sanity check of the state
all-workers-3.0-pre-clean-shutdown because the new kubelet
configuration is already applied, but the old kubernetes version
is still running before the reboot
This is a corner case and our other states would have to be adapted
as well to re-run configs when a node gets accidentally rebooted
and the config hasn't been applied yet.
Furthermore this is only an issue coming from v2 during migration
to v3 - so the case that this happens is even rarer.
Trying to run this state on each worker would require a check for …

[k8s 1.10] don't run haproxy states when not really needed

---

salt/orch/update.sls

in case of a kubernetes update from 1.9 to 1.10 we can't afford
to stop kubernetes through the haproxy states, because it will
not be able to restart as the --config file flag has changed
between those releases
the update orchestration fails in the sanity check of the state
all-workers-3.0-pre-clean-shutdown because the new kubelet
configuration is already applied, but the old kubernetes version
is still running before the reboot
This is a corner case and our other states would have to be adapted
as well to re-run configs when a node gets accidentally rebooted
and the config hasn't been applied yet.
Furthermore this is only an issue coming from v2 during migration
to v3 - so the case that this happens is even rarer.
Trying to run this state on each worker would require a check for …

[3.0][k8s 1.10] don't run haproxy states when not really needed

---

salt/addons/dex/manifests/20-deployment.yaml

Dex pods should run only on master nodes due to firewall/security policies that could be applied to workers nodes.

Fix bsc#1116005: Dex pods should run only on master nodes

---

salt/_modules/caasp_etcd.py
salt/_modules/caasp_net.py

When the default nodename that is used by salt changes duplicates would be added to `etcd`.
This pull request checks if a given nodename might be known to the cluster by an alias.
If any of the aliases is already an `etcd` member, then no changes are performed.
This `PR` also fixes the wrong `key` used to get the current `etcd api version` from a `pillar`.

Fix etcd member addition on nodename changes

---

salt/_modules/caasp_cri.py
salt/migrations/cri/clean-up-crio-pods.sh
salt/migrations/cri/pre-update.sls
salt/orch/update.sls

Backport of #693 
(cherry picked from commit 0d30835a426e7d3caa8e1b096552122b21d2d014)

[3.0] Workaround bsc#1116933: remove /var/lib/container on crio installation

---

salt/_modules/caasp_cri.py
salt/migrations/cri/clean-up-crio-pods.sh
salt/migrations/cri/pre-update.sls
salt/orch/update.sls

This will remove the complete `/var/lib/containers` folder on every update as long as the `crio` version is `1.9.*` - once the crio version does not match `1.9.*` it will no longer remove the directory.

Workaround bsc#1116933: remove /var/lib/container on crio installation

---

salt/migrations/cri/pre-update.sls

This is a workaround for https://github.com/saltstack/salt/issues/14553 when
upgrading crio 1.9 to 1.10.
Backport of #698 
(cherry picked from commit 1e20516f8e67faddfb5c2dead773cdef2abe5331)

[3.0] Fix bsc#1116933: Add a dummy state to prevent empty state in orch

---

pillar/params.sls
salt/kubernetes-common/openstack-config.jinja

Ignore OpenStack Cinder avability zone when attaching volumes.
When Nova and Cinder have different availability zones,
this should be set to true. Default is false.
(cherry picked from commit 8ded363da94c017cad364b0efc08da6f0fc77c22)

[3.0] [CPI] Add option to ignore OpenStack Cinder availability zone, bsc#1095572

---

salt/addons/dex/manifests/20-deployment.yaml

Dex pods should run only on master nodes due to firewall/security policies that could be applied to workers nodes.
(cherry picked from commit 97f9dab742bd8250b790f67e2edd454f06ca2ed0)
Backport of https://github.com/kubic-project/salt/pull/688

[3.0] Fix bsc#1116005: Dex pods should run only on master nodes

---

salt/_modules/caasp_etcd.py
salt/_states/caasp_hosts.py
tox.ini

Minor changes to fix flake8 warnings
- use raw strings in regex methods
- inline-suppress an incorrect unused variable warning
- update to flake8 version 3.6.0 (release notes: http://flake8.pycqa.org/en/latest/release-notes/3.6.0.html)
- switch flake8 config to use new extend-ignore option ("ignore" is an exclusive list, so overrides the default ignored list)

Minor cleanup for flake8

---

Jenkinsfile.tests

Maintenance update 9039 on opensuse increased `pluggy` version to 0.6.0. This
rendered `python3-tox` unusable with that pluggy version, as the current version
in OBS requires `pluggy` (pluggy>=0.3.0,<0.4.0).
Since this is making salt pipelines fail we are including the `python3` environment
on the regular `jenkins-tox-container`.
[1] https://build.suse.de/request/show/182868

Use `jenkins-tox-container` image instead of `jenkins-tox3-container` image

---

salt/addons/dex/manifests/15-configmap.yaml

Backport OIDC support to 3.0 release.  WIP until I can get the 3.0 release to actually build, so creating the PR makes me feel like I've accomplished _something_.
(cherry picked from commit 9ef0f58a26a90eecbdb5a93425c0b94f8cc25581)

3.0-backport: Add support for OIDC connectors to dex configmap (bsc#1116376)

---

salt/kubelet/stop.sls

we want to ensure that the platform 'survives' even if an application
is not 'drainable'
it already happened that some applications are getting stuck in a
termination process and won't recover anymore. This can happen for
various reasons (volume not detachable, podDisruptionBudget ...)
as we are using the drain during every update, we are likely to run
into this issue multiple times per cluster

[bsc#1116049] don't fail timing out on a drain

---

salt/kubelet/kubelet-config.jinja

Fixes: bsc#1114812
Fixes: bsc#1123650
(cherry picked from commit 7776b4b237d6bb3776a579d74e8294017b82f1a8)
Backport of https://github.com/kubic-project/salt/pull/681

[3.0] Enable `ExperimentalCriticalPodAnnotation` feature gate in the kubelet

---

salt/_modules/caasp_filters.py
salt/_modules/tests/test_caasp_filters.py

As it appears, for Python 2 Salt is using a custom module for providing the
ipaddress from Python 3. This implementation turned out to have
bugs (e.g. accepting something70.domain.net as a valid IPv4 record). I've
re-implemented the is_ip* functions so they are using socket.inet_pton instead,
which should suffice in our use case.
bsc#1123291

caasp_filters: properly parse IP addresses

---

salt/kubelet/stop.sls

we want to ensure that the platform 'survives' even if an application
is not 'drainable'
it already happened that some applications are getting stuck in a
termination process and won't recover anymore. This can happen for
various reasons (volume not detachable, podDisruptionBudget ...)
as we are using the drain during every update, we are likely to run
into this issue multiple times per cluster
(cherry picked from commit 73b87c4f7bac62678a009aff73257aa4399b8d5c)
Backport of https://github.com/kubic-project/salt/pull/709

[3.0][bsc#1116049] don't fail timing out on a drain

---

salt/crio/crio.conf.jinja

The pause image was hardcoded in the CRI-O configuration. We now use
the same pillar that defines the location of the pause image and set
it in the cri-o configuration.
Fixes: bsc#1123469

Use pillar location of the pause image for CRI-O

---

Jenkinsfile.flake8
Jenkinsfile.tests

The tox and flake8 pipelines are the only ones which depend on the k8s
Jenkins plugin. As such, we can use docker directly in order to be able
to drop the plugin from the server. The nodelabel is hardcoded because it
does not make much sense to make this configurable given everything happens
on a container.

Jenkinsfile: Use docker cmdline directly instead of k8s Jenkins plugin

---

salt/cni/kube-flannel-rbac.yaml.jinja
salt/cni/kube-flannel.yaml.jinja

Fixes bsc#1121153 - High Security issue for Kubernetes:
Flannel container runs in privileged mode
This fix makes sure that flannel runs in unprivileged mode.
This is done by changing the flannel manifests and also adding
a new PSP policy that disables both privilege mode and privilege
escallation.
The new PSP activates 'NET_ADMIN' capability, hostNetwork
and allowedHostPaths.
* Fixes bsc#1121154 - High Security issue for Kubernetes:
Flannel container has read/write access to /run, including docker.sock
Change the path from '/run' into '/run/flannel'
Co-authored-by: chentex <vzepedamas@suse.com>
(cherry picked from commit 8216c9ce691c8174eb2fcd66a1a2fecc446ee106)

Run flannel in unprivileged mode (bsc#1121153 bsc#1121154)

---

pillar/top.sls
pillar/volume.sls
salt/kube-controller-manager/controller-manager.jinja
salt/kubelet/init.sls
salt/kubelet/kubelet.jinja

* Use a writable directory for volume plugins
* Use the same volumes plugins directory for the `controller-manager` and the `kubelet`
bsc#1117942

bsc#1117942: fixes for volume plugins

---

salt/kube-apiserver/apiserver.jinja

* Fixes bnc#1121148 - Critical Security issue for KubeAPI
Insecure API port exposed to all Master Node guest containers
In older versions of Kubernetes, you could run kube-apiserver
with an API port that does not have any protections around it.
This PR disables insecure port by passing the --insecure-port=0
In recent versions, this has been disabled by default with the
intention of completely deprecating it
(cherry picked from commit 01d91482e9a84b05b3b6eaec6a94b7b19ee74ee4)

Disable insecure port in kube-apiserver (bsc#1121148)

---

salt/orch/kubernetes.sls

On realy slow deployments salt-minion-ca can exceed timeouts
for "ca-setup" and "generate-sa-key" modules. We can avoid this
and add timeout option to "generate-sa-key".
Option "timeout" is the maximum time in seconds to wait before failing.

Increase timeout for salt-minion-ca modules, bsc#1108470

---

salt/_modules/caasp_hosts.py
salt/_modules/tests/test_caasp_hosts.py

Salt will pick the first name on the current default interface to determine
the hostname of the machine. Since we are sorting with all entries for each
machine there's a high change that a salt minion id will win the first position,
affecting certain grains that we use to determine the hostname of the node.
With this change we are not only sorting alphabetically by the name of each column
in each entry, but also adding weight to each column on each entry. This means that
the nodename will always win, as its primary weight will be lower than the rest,
while the second sorting strategy is purely alphabetical.
Fixes: bsc#1117339

Sort nodenames first when generating /etc/hosts entries

---

salt/_macros/kubectl.jinja

instead of setting the timeout we were setting the retries which
causes the timeout to be prolonged too much

[bsc#1125095] deployment timeout not correctly configured

---

Jenkinsfile
Jenkinsfile.flake8
Jenkinsfile.housekeeping
Jenkinsfile.tests

Instead of having the library hardcoded to Jenkins master, we can fetch
it dynamically. We also drop the usage of library branches since it does
not make sense to maintain such a thing in the CI. The master branch
should be able to handle both development and release branches.

Jenkinsfile: Switch to dynamic library fetching and drop branch

---

salt/_modules/caasp_net.py

In python3 python prevents modifying the dictionary that is iterated over.
Instead of modifying the initial dictionary it will be copied first.
Also `iteritems` is no longer available in `python3`, so the code should use the `six` function instead to be cross-version compatible.

Fix python3 iteration over dictionary.

---

salt/migrations/cri/pre-update.sls

This is a workaround for https://github.com/saltstack/salt/issues/14553 when
upgrading crio 1.9 to 1.10.

Add a dummy state to not have an empty state in an orchestration

---

salt/_states/caasp_file.py
salt/haproxy/init.sls
salt/migrations/2-3/haproxy/init.sls

When using `file.managed`, create a temporary file that is in `/tmp` instead of using the same directory the target file is. This fixes some problems with programs/daemons that could be monitoring that directory (like the `kubelet` with `/etc/kubernetes/manifests`)
bsc#1123716

Use a temporary file in /tmp for file.managed

---

salt/_modules/caasp_orch.py
salt/orch/etcd-migrate.sls
salt/orch/force-removal.sls
salt/orch/kubernetes.sls
salt/orch/prepare-product-migration.sls
salt/orch/removal.sls
salt/orch/update-etc-hosts.sls
salt/orch/update.sls

* Synchronize everything before starting an orchestration.
* Replace all the `mine.get` calls by the more compact `get_with_expr` function.
bsc#1124784

Synchronize everything before starting an orchestration.

---

salt/kube-apiserver/apiserver.jinja

When a cluster is bootstrapped with multiple kube-apiservers, the `kubernetes`
service contains a list of all of these endpoints.
By default, this list of endpoints will *not* be updated if one of the
apiservers goes down. This can lead to the api becoming unresponsive and
breaking it. To have the endpoints automatically keep track of the apiservers
that are available the `--endpoint-reconciler-type` option `lease` needs to be
added.
(The default option for 1.10 `master-count` only changes the endpoint when the
count changes: https://github.com/apprenda/kismatic/issues/987)
See:
https://github.com/kubernetes/kubernetes/issues/22609
https://github.com/kubernetes/kubernetes/issues/56584
https://github.com/kubernetes/kubernetes/pull/51698
Fixes bsc#1098664

Automatically update the kubernetes-service endpoint.

---

salt/kubelet/kubelet-config.jinja

Enabling Token authentication allows external
components like monitoring tools to fetch information
against kubelet on port 10250 over HTTPS and authenticate
with a Bearer token.
Fixes bsc#1127326
Signed-off-by: Ludovic Cavajani <lcavajani@suse.com>
(cherry picked from commit c4005e5288496ade4f5e50392538356ea5b40061)

[bsc#1127326] Enable Kubelet token authentication

---

salt/_modules/caasp_hosts.py
salt/_modules/caasp_net.py

This PR adds fixes that were needed to make an update from a v2 to a v3 cluster succeed:
- generating the `/etc/hosts` file failed, because the backup location did not exist.
- checking `etcd` membership would (wrongly) fail, because only the list of aliases for either the `ipv4` or `ipv6` addresses would be checked, instead of both.

bsc#1120717: Check all aliases for etcd member check and create /etc/caasp directory before access

---

salt/_modules/caasp_nodes.py
salt/orch/update.sls
salt/transactional-update/init.sls

When executing the update orchestration, it's not always desired to reenable the
transactional-update. Moreover, sometimes the timer was on a weird state if the
update failed. This commit refines the update orchestration following this
logic:
1. Check first which nodes have explicitely disabled the timer, so they are not
reenabled in the end.
2. Disable the timer at the very beginning.
3. If this is a migration, reenable it always.
4. Otherwise, reenable the timer only for these nodes which did not explicitely
disable it before the update.
Last but not least, I've also tweaked the `transactional-update/init.sls` file
so the timer is not touched by this file when updating.
bsc#1113518

Don't always reenable the transaction-update timer on update

---

config/master.d/50-reactor.conf
reactor/sync-modules.sls

we sync modules already in different places during orcherstration
so it is not needed to sync modules
( sync-modules in saltstack actually can create race-conditions so better to remove it if not needed)

Remove sync-modules from reactor

---

salt/_macros/certs.jinja
salt/_modules/caasp_grains.py
salt/ca-cert/init.sls
salt/kube-apiserver/apiserver.jinja
salt/kubernetes-common/serviceaccount-key.sls
salt/orch/force-removal.sls
salt/reboot/init.sls

DeprecationWarning: the target type should be passed using the 'tgt_type' argument instead of 'expr_form'.
Support for using 'expr_form' will be removed in Salt Fluorine.

Fix deprecationWarning: tgt_type in logs

---

salt/orch/update.sls

The `uncordon_node` can be set when begining an update if a previous update failed. This PR makes sure this grain is removed in the whole cluster when starting the update.

Cleanup uncordon_node grain before update (bsc#1111173)

---

salt/haproxy/haproxy.cfg.jinja

Internal api endpoints exposes sensitive data and this cannot be
accessed via internet.
This internal api was developed inside velum project and haproxy was
allowing the request to that endpoint. Velum listens on 0.0.0.0 and
needs to block for that specific path.
With this patch we are blocking any request to anything that starts
with /internal-api.
Signed-off-by: Vítor Avelino <vavelino@suse.com>
bsc#1121162

[bsc#1121162] haproxy: block requests to /internal-api endpoint

---

salt/proxy/init.sls

Remove the proxy config files when `proxy:systemwide` is not set (or set to False).
[bsc#1116572](https://bugzilla.suse.com/show_bug.cgi?id=1116572)

Remove the proxy config files when `proxy:systemwide` is not set

---

config/master.d/50-reactor.conf
reactor/presence.sls
reactor/sync-grains.sls
reactor/update-mine.sls

we shouldn't sync grains/update mine during start minions. ( a part of slowing down orchestration and minion we don't needed this)

Cleanup unneeded reactor code

---

salt/_modules/caasp_net.py
salt/kube-apiserver/init.sls
salt/kube-apiserver/stop.sls

For limiting access to KUBE-APISERVER on port 6444 only connection
from localhost and CaaSP cluster nodes should be allowed,
rest of the traffic should be forbidden.

Limit access to KUBE-APISERVER port 6444 on master nodes, bsc#1121144

---

config/master.d/50-master.conf
pillar/certificates.sls
salt/_macros/certs.jinja
salt/addons/dex/init.sls
salt/addons/dex/wait.sls
salt/haproxy/haproxy.cfg.jinja
salt/haproxy/haproxy.yaml.jinja
salt/haproxy/init.sls
salt/kube-apiserver/init.sls
salt/kube-apiserver/remove-pre-orchestration.sls
salt/kubeconfig/kubeconfig.jinja
salt/orch/refresh-certs.sls
salt/velum/init.sls

All the salt backend changes to make Velum, Dex, and kube-API (the external-facing services) support user-provided Certs (and their corresponding CA).
There is a related PR in kubic-project/caasp-container-manifests#213 which is necessary for this to work properly.
Marked work-in-progress since it's still not completely verified as working.

User cert support

---

config/master.d/50-master.conf

By default, SUSE Manager globally sets timeout and gather_job_timeout to 120 seconds.
So, in the worst case, a Salt call targeting unreachable minions will end up with
240 seconds of waiting until getting a response.

Adjust timeouts for the salt command and api (bsc1130242)

---

salt/orch/kubernetes.sls
salt/orch/refresh-certs.sls

Update kubernetes orchestration to restart kublet and salt-minion processes when the CA store changes.
Also fix cert-specific orchestration
This is "finishing" the User-provided SSL cert feature (SUSE/caasp-playground#170 and SUSE/caasp-playground#171). Once merged, will get added in to SUSE/kubic-salt-security-fixes#44.

restart kubelet & salt-minion on cert change (bsc#1131568)

---

salt/orch/update.sls

In the update process we disable the transactional update timer and re
enabled it after update the machine. However, just re enable it is not
enough. We need to start the timer. Otherwise, the update service will
not run and consequently no updates is installed. This commit adds in
the update.sls a step to start the timer after re enabling it.
bsc#1141675
Signed-off-by: José Guilherme Vanz <jguilhermevanz@suse.com>

update.sls: start transactional-update timer
